Fix empty global search
elementary/code pull request #1011
Opened 2021-04-29 10:31 UTC by jeremypw

Fixes #1008 

Also rebases the dialog on Granite.MessageDialog, similar to the NewBranchDialog.

2021-04-29 10:33 UTC, jeremypw commented
![GlobalSearchDialog](https://user-images.githubusercontent.com/10513844/116537864-b3f02d00-a8de-11eb-8190-21ab21bb863a.png)

2021-04-29 18:48 UTC, danrabbit requested changes
I opened #1013 with a few requested changes

2021-04-29 18:48 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +            search_term_entry.is_valid = search_term_entry.text.length >= 3;
Does it really need to be >= 3 or just 0 ?

2021-04-30 07:22 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +            search_term_entry.is_valid = search_term_entry.text.length >= 3;
The rules for legal branch names are quite complicated, but single letter names are accepted by git (not sure if GitHub imposes any additional restrictions).  Not sure where I got the existing Regex and min length from but they need relaxing to exactly match git rules.  I just noticed that there is a `is_valid_name` static function provided in the git library so I'll see if I can use that.

2021-04-30 15:51 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +            search_term_entry.is_valid = search_term_entry.text.length >= 3;
@jeremypw that sounds like a good idea for the git branch, but this is the global search branch ;) Maybe some coffee or sleep? lol

2021-04-30 15:54 UTC, danrabbit approved these changes

2021-04-30 15:54 UTC, merged