NewBranchDialog: Check for existing branches
elementary/code pull request #1012
Opened 2021-04-29 16:41 UTC by jeremypw

Fixes #1004

Also
* Use unowned variables for strings where possible
* MonitoredRepositor: Use list not array for local branch names
* ProjectFolderItem: Public getter function for branch names
* ChangeBranchMenu: Use construct clause

2021-04-29 17:09 UTC, danrabbit requested changes

2021-04-29 17:09 UTC, danrabbit commented on src/Dialogs/NewBranchDialog.vala
> +            secondary_text = ("%s\n%s").printf (secondary_1, secondary_2);
I'm not sure that we should force a line break here, the text should wrap as necessary
```suggestion
            secondary_text = _("The branch name must be lower-case, start with a letter, and be at least 3 characters. The name must not already exist.");
```

2021-04-29 17:09 UTC, danrabbit commented on src/Dialogs/NewBranchDialog.vala
> +                    new_branch_name_entry.is_valid = false;
Shouldn't we break the loop if we find a match?

2021-04-30 06:53 UTC, jeremypw commented on src/Dialogs/NewBranchDialog.vala
> +            secondary_text = ("%s\n%s").printf (secondary_1, secondary_2);
OK, I was concerned that in some locales the break might occur in an awkward position but I guess that could happen anyway.

2021-04-30 07:06 UTC, jeremypw commented on src/Dialogs/NewBranchDialog.vala
> +            secondary_text = ("%s\n%s").printf (secondary_1, secondary_2);
Oh yes, done.

2021-04-30 08:42 UTC, jeremypw commented on src/Dialogs/NewBranchDialog.vala
> +                    new_branch_name_entry.is_valid = false;
I have now replaced this code with an improved method.

2021-04-30 08:43 UTC, jeremypw commented on src/Dialogs/NewBranchDialog.vala
> +            secondary_text = ("%s\n%s").printf (secondary_1, secondary_2);
Text now updated without new line.

2021-04-30 08:44 UTC, jeremypw commented
A possible (future) refinement would be to choose the branch on which to base the new branch.  Currently it is based on the current branch and switches to the new branch like the `git checkout -b new_branch` command.

2021-04-30 16:09 UTC, danrabbit approved these changes

2021-04-30 16:14 UTC, merged