Get diff gutter colors from SourceStyleScheme if possible
elementary/code pull request #1061
Opened 2021-06-03 12:43 UTC by jeremypw

This PR attempts to get colors defined in the current or fallback SourceStyleScheme for ids "diff:added-line" etc otherwise use hard-coded colors.

Unfortunately of the three styles built into Code, only "classic" contains the relevant style ids and none contain a style explicitly for unchanged lines that replace lines that have been deleted.

2021-06-03 19:10 UTC, danrabbit requested changes
Left a couple of inline comments. This looks good and works as expected here! I can see that it is pulling in the colors from the style and updates correctly when changing styles

Since Gtk.SourceView does ship "classic" as part of the library, I don't think we need any fallbacks other than pulling from this style, and I think we can assume it exists and won't return null etc

2021-06-03 19:10 UTC, danrabbit commented on src/Widgets/SourceGutterRenderer.vala
> +        fallback_scheme = Gtk.SourceStyleSchemeManager.get_default ().get_scheme ("classic"); // Assume this always exists?
Classic is shipped with Gtk.SourceView, so I think it's safe to assume it always exists. We probably don't need null checks etc for this: https://gitlab.gnome.org/GNOME/gtksourceview/-/tree/master/data/styles

2021-06-04 08:54 UTC, jeremypw commented
Thanks for the review - I did fear this was somewhat over-engineered.  I'll simplify as you suggest.

2021-06-04 10:40 UTC, jeremypw commented on src/Widgets/SourceGutterRenderer.vala
> +            update_status_color_map (Services.VCStatus.NONE, get_style (scheme, NONE_STYLE_ID, false), false);
Removed

2021-06-04 10:40 UTC, jeremypw commented on src/Widgets/SourceGutterRenderer.vala
> +        fallback_scheme = Gtk.SourceStyleSchemeManager.get_default ().get_scheme ("classic"); // Assume this always exists?
Builtin fallback removed, checks removed

2021-06-04 10:42 UTC, jeremypw commented
I have increased the gutter width to 5px as I was having trouble distinguishing the more muted classic colors with a 3px gutter.

2021-06-04 16:04 UTC, danrabbit commented
Looks great. Nice work!

2021-06-04 16:04 UTC, merged