Update ChooseProjectButton when a project is closed.
elementary/code pull request #1101
Opened 2021-09-07 20:40 UTC by igordsm

Fix #1075 . When a project is closed check if it is the currently active project (as selected in ChooseProjectButton) and resets active project to no active project state.

2021-09-08 17:44 UTC, jeremypw requested changes
Does the main job.  Just a query about the tooltip.

2021-09-08 17:44 UTC, jeremypw commented on src/Widgets/ChooseProjectButton.vala
> +                label_widget.tooltip_text = _("Active Git project: %s").printf (_(NO_PROJECT_SELECTED));
I think a more helpful tooltip could be given here.  How about "Open a document in a project folder"? As it is, there is only an "active project" when there is a project folder open in the sidebar AND one of its documents is open.  Maybe this logic needs rethinking as it can be a bit confusing.  There is no direct way of "selecting" a project so "No project selected" probably needs changing too, but that could wait for a different PR.

2021-09-09 15:27 UTC, igordsm commented on src/Widgets/ChooseProjectButton.vala
> +                label_widget.tooltip_text = _("Active Git project: %s").printf (_(NO_PROJECT_SELECTED));
Well, I just copied the default label and tooltip set when the widget is created. How about raising a new issue to discuss this? IMHO the tooltip could show different things when there are project folders but the user hasn't selected an active one and no project folders are opened.

2021-09-09 17:55 UTC, jeremypw commented on src/Widgets/ChooseProjectButton.vala
> +                label_widget.tooltip_text = _("Active Git project: %s").printf (_(NO_PROJECT_SELECTED));
OK, if you want to leave it for another PR that's OK.  This PR is still an improvement.

2021-09-09 17:55 UTC, jeremypw approved these changes

2021-09-28 17:09 UTC, merged