Rewrite word completion to play nice with other completion providers.
elementary/code pull request #1125
Opened 2021-11-13 12:28 UTC by igordsm

This makes word completion work with Snippets from #1113 . It's an extensive rewrite of the plugin, so there are probably lots of possible improvements. I've been using it without much problem in the last hours, so I'm sending for review.

2021-11-17 12:52 UTC, jeremypw reviewed
This looks good to me.  I'll merge it together with the snippets branch into my "merge-dev-fixes" branch and dogfood it for a day or two.

There are a couple of other things that could be improved in the original but they are not related to this issue so I'll submit separate PRs for those.

2021-11-17 12:52 UTC, jeremypw commented on plugins/word-completion/engine.vala
> +        return list.length () > 0;
Its more efficient to test whether the beginning of the list is null than to measure its length.

2021-11-17 13:11 UTC, jeremypw requested changes
One issue I noticed that this PR introduces is that in some cases a prefix matches both a word and the same word followed by a space.

On a blank line type a (new) word
On the next line type the same word followed by a space
On the next line start typing the same word again - the completion shows two entries that are visually the same but one contains an extra space

2021-11-18 01:41 UTC, igordsm commented
Just pushed changes that should address this problem, @jeremypw . Thank you for the instructions to reproduce it.

2021-11-18 11:56 UTC, jeremypw commented
I can confirm that the above issue with spaces is fixed.  I'll dogfood for a day or two to see if anything else arises.

2021-11-20 17:24 UTC, jeremypw commented on plugins/word-completion/engine.vala
> +        return list.is_empty ();
GLib.List does not have this function.

2021-11-20 22:27 UTC, igordsm commented on plugins/word-completion/engine.vala
> +        return list.is_empty ();
Strange, I looked up at [valadoc](https://valadoc.org/glib-2.0/GLib.List.is_empty.html) and it exists. VLS also suggests it for me, but build is failing... I'm using Vala 0.54, but didn't expect this to create problems.

2021-11-20 23:41 UTC, igordsm commented on plugins/word-completion/engine.vala
> +        return list.is_empty ();
Confirmed that `is_empty` fails build on vala 0.48.

2021-11-21 11:34 UTC, jeremypw commented on plugins/word-completion/engine.vala
> +        return list.is_empty ();
I notice that it is an inline Vala function - there is no C function`g_list_is_empty`  Maybe it requires a later version of Vala (or GLib).

2021-11-21 11:45 UTC, vjr commented on plugins/word-completion/engine.vala
> +        return list.is_empty ();
@igordsm  I noticed that the previous code was like `length > 0` so the `is_empty` check should have been inverted?

But anyway looks like you replaced it with a different check, not sure how safe it is though.

2021-11-21 18:21 UTC, igordsm commented on plugins/word-completion/engine.vala
> +        return list.is_empty ();
@vjr yeah, I noticed that as well when replacing it. Current code is correct, but thanks for the warning.

2021-12-08 10:18 UTC, jeremypw requested changes

2021-12-08 10:18 UTC, jeremypw commented on plugins/word-completion/engine.vala
> +    public const string DELIMITERS = " .,;:?{}[]()0123456789+-=&|-<>*\\/\r\n\t\'\"`";
I would not consider hyphen and underscore as delimiters (see my separate PR on this issue).  If you agree, could you change it here?

2021-12-13 16:44 UTC, jeremypw commented
@igordsm I'd like to merge this as soon as possible - are you able to address the space/hyphen issue?

2021-12-15 12:04 UTC, jeremypw approved these changes

2021-12-15 14:56 UTC, merged