Fix various typos
elementary/code pull request #1133
Opened 2021-11-19 23:18 UTC by luzpaz

Found via `codespell -q 3 -S *.po,./po`

2021-11-20 16:57 UTC, jeremypw requested changes
Thanks!  Just one thing the tool corrected in the wrong way.

2021-11-20 16:57 UTC, jeremypw commented on src/Widgets/SearchBar.vala
> +                debug ("Can't search anything in an inexistent buffer and/or without anything to search.");
Should actually be `non-existent`

2021-11-20 23:13 UTC, luzpaz commented on src/Widgets/SearchBar.vala
> +                debug ("Can't search anything in an inexistent buffer and/or without anything to search.");
@jeremypw fixed in d651bdd

2021-11-21 11:31 UTC, jeremypw commented on src/Widgets/SearchBar.vala
> +                debug ("Can't search anything in an non-existent buffer and/or without anything to search.");
Sorry I should have said that the article will need to be changed as well.
```suggestion
                debug ("Can't search anything in a non-existent buffer and/or without anything to search.");
```

2021-11-22 13:18 UTC, jeremypw approved these changes

2021-11-22 13:19 UTC, merged