Move strip trailing whitespace into main code; remove plugin
elementary/code pull request #1151
Opened 2021-12-08 18:03 UTC by jeremypw

Fixes #1098 
Fixes #581

2021-12-13 16:05 UTC, jeremypw commented
Bug found - converting to draft while fixing.

2022-08-11 13:46 UTC, jeremypw commented
Reduced scope of PR so that current behaviour (strip only on manual save or close) is unaffected.  Stripping on autosave would be easy to add later if required.

2022-08-11 13:50 UTC, jeremypw commented
The problem with CI appears unrelated to this PR - it compiles OK locally.

2022-08-20 04:55 UTC, zeebok approved these changes
This looks good to me

2022-08-20 04:55 UTC, zeebok commented on src/Services/Document.vala
> +            if (!loaded || source_view.language == null || source_view.language.id != "vala") {
Does this mean this "plugin" code only supports vala files?

2022-08-20 08:03 UTC, jeremypw commented on src/Services/Document.vala
> +            if (!loaded || source_view.language == null || source_view.language.id != "vala") {
Hmm, its a while since I wrote this and I don't recall why I put that restriction in - it does not seem to be in the original plugin.   I guess if working with a language where trailing spaces are significant then you would not have this function active anyway.

2022-08-20 17:21 UTC, jeremypw commented on src/Services/Document.vala
> +            if (!loaded || source_view.language == null || source_view.language.id != "vala") {
I have now removed this restriction to avoid behavior change in this PR.

2022-08-20 17:23 UTC, jeremypw commented
A possible refinement is to have the "strip trailing whiltespace" functionality independent of saving so that it occurs even if "autosave" is off.

2022-08-21 02:26 UTC, zeebok commented
Hmmm how would that look separated from saving? Remove the trailing white space when a user starts a new line?

2022-08-21 09:14 UTC, jeremypw commented
No, I found it too intrusive for stripping to occur immediately after leaving a line. For example,  I like to insert a blank line and the closing brace of an `if () {}` clause then go back and fill in the body of the clause - I do not want the indenting spaces to be removed at that point.   The stripping would still occur when losing focus - e.g. switching to another document or a terminal even if the document is not autosaving.  At the moment with master I have to consciously press `<Ctrl>S` on each document before running `vala-lint`.

2022-08-22 02:34 UTC, zeebok commented
Gotcha. Do you think that might not do it often enough? If I write a quick fix, or just code for a short time, in a single doc and close Code it sounds like it wouldn't strip. Not a frequent scenario but one I can picture happening.

2022-08-22 07:47 UTC, jeremypw commented
I think #1188  might be relevant here - this could also ensure stripping occurs.

2022-08-22 16:25 UTC, zeebok commented
Yeah that seems good. Personally the more places it checks and does the stripping without interfering the better so it ensures a consistent experience. Losing focus, on saves, etc are all good places to me.

2022-08-22 16:27 UTC, jeremypw commented
@zeebok Is it OK to merge this PR (which should behave pretty much the same as master, without regressions) and make changes to behaviour in future PRs?

2022-08-31 17:34 UTC, danrabbit requested changes
I am in favor of moving plugins into the main source for sure :+1: 

Instead of using the phrase "blacklist" here, can we use "blocklist" instead?

2022-08-31 21:50 UTC, Marukesu commented
> An issue raised by this is what to do about the already installed plugin - this PR overwrites it so that it does not appear in the Extensions dialog. Alternative solutions welcome.

I think this should be handled from the package side, for source installations, we should recommend doing an `sudo ninja uninstall` before a new `ninja install`, so that old plugins get removed.

For the deb package, aren't plugins installed in the same package? so when an update occurs, they all got removed and only the ones in the new build installed?

the flatpak package aren't affected by this.

2022-09-01 07:59 UTC, jeremypw commented
@Marukesu I didn't realise Code has an `uninstall` ninja target - not all projects (e.g. Files) have one. In that case, and in view of the fact that Flatpaks are unaffected I will remove the relevant code from this PR.  I am uncertain whether just updating a deb will remove old plugins though.

2022-09-01 21:29 UTC, danrabbit commented
Yeah the Deb package will cleanup old installed files like plugins so this only affects source installs

2022-10-04 06:37 UTC, zeebok approved these changes

2022-10-04 15:11 UTC, merged