Use `org.freedesktop.portal.OpenURI` for Providing the AppChooser
elementary/code pull request #1162
Opened 2021-12-17 19:36 UTC by Marukesu

supersedes #1029

Make use of the OpenURI portal for showing an AppChooser and for opening the file on the File Manager.

This one can be used on host too.

2021-12-18 18:52 UTC, jeremypw requested changes
A few comments but otherwise this works as expected and the code looks good.

2021-12-18 18:52 UTC, jeremypw commented on src/FolderManager/FileItem.vala
> +            var files_menuitem = new Gtk.MenuItem.with_label (_("File Manager…"));
There should not be an ellipsis here as that indicates a submenu or chooser will appear

2021-12-18 18:52 UTC, jeremypw commented on src/FolderManager/Item.vala
> +                // the OpenDirectory method was added on version 3
```suggestion
                // the OpenDirectory method was added in version 3 of the portal
```

2021-12-18 18:52 UTC, jeremypw commented on src/FolderManager/Item.vala
> +                options["writable"] = !file.is_valid_directory ();
Cannot actually assume the file is writable - if it isn't the menu option fails with a terminal warning.  Should probably make the option insensitive (or remove it) for unwritable files.

2021-12-19 03:29 UTC, Marukesu commented
Added a new property on `FolderManager.File` to query write access, this should work with both read-write and read-only files and directories.

2022-05-04 18:44 UTC, jeremypw reviewed
Sorry for overlloking this for so long.

Is there a reason for the context menu for folder items to differ from that for file items (compared to master running natively)?  The former has an ellipsis and launches straight into the AppChooser whereas the latter has a submenu offering an immediate option to open in the FileManager as well as an "Other applications" option (which offers the File Manager).

Otherwise this is looking good.  Will changing to the OS7 platform require any changes?

2022-05-05 17:43 UTC, Marukesu commented
> Is there a reason for the context menu for folder items to differ from that for file items (compared to master running natively)? The former has an ellipsis and launches straight into the AppChooser whereas the latter has a submenu offering an immediate option to open in the FileManager as well as an "Other applications" option (which offers the File Manager).

Since we don't have access to the AppInfo inside the sandbox, the submenu in `FolderItem` had only one option (`AppChooser`), so i removed it, while, `FileItem` ended with three (`New Window`, `File Manager`, `AppChooser`).

In master, the file manager entry is created manually by querying the default AppInfo for `inode/directory`, the portal has the  `OpenURI.open_directory()` method to replace this case, so i used it. Also, i can't see the File Manager in the AppChooser for `FileItem` here.

> Will changing to the OS7 platform require any changes?

You say the flatpak runtime? since we are using Gtk3 here, no changes should be needed. For Gtk4, we need to adapt the `MainWindow.export()` code to use `Gdk.Surface` instead of `Gdk.Window`.

2022-05-05 18:45 UTC, Marukesu commented
> I still do not really see why a fileitem and a folderitem should have a different "Open in..." submenu. Can we not offer a "Open in FIleManager" item for folder items as well as file items?

we can, but it's less useful for folders, since the AppChooser will show the FileManager anyway. that not the case for files.
 
> It could make sense to offer a "New Window" option for folders as well as files but that is outside the scope of this PR.

Well, projects folders aren't unique per-window, so any new window will already have all the folders anyway.

2022-05-06 08:31 UTC, jeremypw approved these changes

2022-05-06 08:42 UTC, tintou commented
Sorry for taking so long for reviewing it, but I don't understand what are you solving here?

2022-05-06 08:44 UTC, tintou commented
Implementing the OpenURI portal inside Code is not the way to go, a portal implementation has to be out of the container

2022-05-06 08:46 UTC, tintou commented on src/FolderManager/FolderItem.vala
> +            var open_in_item = new Gtk.MenuItem.with_label (_("Open In…"));
It has to be something like:
```suggestion
            var open_in_item = new Gtk.MenuItem.with_label (_("Open in another application…"));
```

2022-05-06 08:49 UTC, tintou commented
The only way to trigger a portal for opening a file would be:
```
GLib.AppInfo.launch_default_for_uri (file.file.get_uri (), null);
```

2022-05-06 08:53 UTC, tintou commented
@danrabbit We should make a blog post about how app developers should replace the in-app "Open In…" menus with something that works in containers

2022-05-06 16:21 UTC, danrabbit commented
@tintou yeah the problem is there isn't a replacement portal yet :sweat_smile: https://github.com/elementary/portals/pull/38

2022-05-14 12:51 UTC, jeremypw commented
@danrabbit So should this PR be blocked pending a wrapper for the OpenUri portal appearing in Gtk or Granite, which it can then use?

2022-05-14 16:50 UTC, danrabbit commented
@jeremypw it seems like generally the OpenURI Portal probably isn't the appropriate portal to use here long-term anyways so this is more of a work around to preserve some functionality inside the sandbox. The proper long-term solution would be to create a sharing portal that's actually designed for this. Since we're not shipping Code in a Flatpak currently, I'm not sure this specific workaround is a huge priority? We could probably wait for a new portal?

2022-05-15 08:15 UTC, jeremypw commented
The only "Open in ..." functionality I use is "Open in Terminal".

2023-08-02 15:02 UTC, closed without merging