Search Dialog Regex Support
elementary/code pull request #1170
Opened 2022-02-14 21:54 UTC by mariusgassen

2022-02-15 19:14 UTC, jeremypw commented
Thanks for the PR but please do not update the po files - that happens automatically once the PR is merged.  Will review as soon as I can.

2022-02-21 18:33 UTC, jeremypw requested changes
The regex functionality works pretty much as expected but this PR introduces a regression even when the Regex button is not active.

If some search text is entered and at least one match is found, if you then enter a character into the document the cursor jumps to the start of the next match immediately after the text is entered. This is not expected.  You should be able to enter text into the document as normal while a search is active.

2022-02-21 18:35 UTC, jeremypw commented
@mariusgassen  I notice you pushed some changes while I was reviewing.  If you are still making significatnt changes to this PR please convert it to "draft".  It needs to be in a stable state for reviewing.

2022-02-21 19:58 UTC, mariusgassen commented
> @mariusgassen I notice you pushed some changes while I was reviewing. If you are still making significatnt changes to this PR please convert it to "draft". It needs to be in a stable state for reviewing.

Sorry, I was fixing the linter issue from the workflow while you seem to have been reviewing the PR.

> The regex functionality works pretty much as expected but this PR introduces a regression even when the Regex button is not active.
> 
> If some search text is entered and at least one match is found, if you then enter a character into the document the cursor jumps to the start of the next match immediately after the text is entered. This is not expected. You should be able to enter text into the document as normal while a search is active.

I now fixed the jumping cursor that happened on entering new text with existing search results.
This stemmed from the reenabled replace actions fix: when changing the document text a full search was performed including selection range updates to the next search result. This is no longer the case

2022-02-23 19:00 UTC, jeremypw requested changes
A couple of minor comments.  There seem to be several changes not essential to the aim of this PR.  While these may well be improvements it is best to keep the diff as small as possible to be easier to review.  Code style and other improvements could be submitted separately.  I understand the temptation though - I do it myself!

2022-02-23 19:11 UTC, mariusgassen commented on src/Widgets/SearchBar.vala
> -
I reordered the fields to place the comment next to the field it describes because it seemed orphaned and then decided the field was rather self-explanatory. I can readd it to keep the diff smaller though.

2022-03-01 11:01 UTC, jeremypw approved these changes

2022-03-01 11:02 UTC, jeremypw commented
I think this can be merged and, if required, iterated on now.  Thanks for the contribution!

2022-03-01 11:02 UTC, merged