Fix occasional crash in SearchBar
elementary/code pull request #1174
Opened 2022-03-08 19:21 UTC by jeremypw

Fixes #1173 

Check null search_context before using; 
Cancel search occurence label update before changing context or textview

This PR should not change any functionality.

2022-03-09 08:53 UTC, davidmhewitt requested changes

2022-03-09 08:53 UTC, davidmhewitt commented on src/Widgets/SearchBar.vala
> +                critical ("Trying to search forwards with no search context");
I would say this is a warning and the method should return in this case? `search_context` is used inside this method and that `null` access is going to cause issues. So better to log a warning and return from the method than log a critical and potentially crash and lose work?

2022-03-09 08:53 UTC, davidmhewitt commented on src/Widgets/SearchBar.vala
> +                critical ("Trying to search backwards with no search context");
Same here

2022-03-09 09:08 UTC, jeremypw commented
@davidmhewitt  Thanks for the review and for spotting those missing returns!

2022-03-09 09:58 UTC, jeremypw commented
A critical message is downgraded as it gets triggered during normal startup due to a toolbar button state being bound to settings before an active document is focused.  It is easier to ignore this rather than try and ensure it doesnt happen.

2022-03-14 11:21 UTC, davidmhewitt requested changes

2022-03-14 11:21 UTC, davidmhewitt commented on src/Widgets/SearchBar.vala
> +            if (search_context == null) {
```suggestion
            if (search_context != null) {
```

This if statement appears to be inverted compared to its indended use?

2022-03-14 18:16 UTC, jeremypw commented on src/Widgets/SearchBar.vala
> +            if (search_context == null) {
Oops!

2022-03-17 13:14 UTC, merged