EditorConfig plugin overrides global settings for indent width and style
elementary/code pull request #1204
Opened 2022-08-13 12:02 UTC by jeremypw

Fixes #1203

* [x] Specify name of editorconfig file so that plugin actually works
* [x] Link editorconfig plugin and format bar
* [x] Expose functions to change indent width and style of current document.
* [x] Make format bar aware if indent width and/or style set by plugin
* [x] If editorconfig plugin sets indent width and/or style, make the formatbar indent button insensitive.
* [x] Amend tab button text and tooltip text accordingly
* [x] Prevent FormatBar changing global settings (this is done via Preferences) 
* [x] Amend `.editorconfig` file so that it does not duplicate/conflict with global setting of indent width and style.

It was noticed that although `indent-width` and `tab-width` are separate properties of SourceView, there is no facility in the existing code for these to be set separately so these are treated the same by the plugin (and only one specified in the config file).  If both were specified in a config file then the last one would have priority. If there are situations where these need to be set separately additional code will be required.

Input required on the user facing copy.

2022-08-31 16:59 UTC, danrabbit requested changes
Hm, this doesn't seem to work for me. When I open an xml file in a project with an editorconfig (such as code) I still get 4 space indent instead of 2

2022-08-31 16:59 UTC, danrabbit commented on src/Widgets/FormatBar.vala
> +        tab_toggle.text = "%d (%s)".printf (
It seems like this if/else is immediately overwritten right?

2022-09-02 10:11 UTC, jeremypw commented on src/Widgets/FormatBar.vala
> +        tab_toggle.text = "%d (%s)".printf (
Oops - looks like both alternatives were left in.  I will remove one.

2022-09-02 10:16 UTC, jeremypw commented
@danrabbit  It works for me under those circumstances.  You have to have 
```
[{*.xml,*.xml.in,*.yml}]
tab_width = 2
```

in the editor-config file (*after* the [*] setting)

2022-09-02 10:18 UTC, jeremypw commented
Also you have to install the PR in order to update the plugin.

2022-09-02 10:22 UTC, jeremypw commented
Maybe this is another candidate for moving into the main code?

2023-01-12 00:56 UTC, danirabbit approved these changes
Works as expected, thanks for fixing this!

2023-01-12 00:57 UTC, merged