Change panel menu items to linkbutton
elementary/code pull request #1223
Opened 2023-01-09 21:17 UTC by danirabbit

Fixes #1213 

![Screenshot from 2023-01-09 13 16 25](https://user-images.githubusercontent.com/7277719/211410003-f7b4f5bb-9629-45ea-b06e-04bda65333ad.png)

* Make toggle actions hold their state
* Change tooltips to reflect show/hide action
* Use linked icon togglebuttons to show/hide panels

2023-01-10 17:52 UTC, danirabbit commented
@jeremypw fixed!

2023-01-12 12:04 UTC, jeremypw requested changes
Just a small simplification suggested inline, otherwise looks good

2023-01-12 21:29 UTC, danirabbit commented on src/MainWindow.vala
>          }
Thanks for the tip! That's much better

2023-01-13 10:34 UTC, jeremypw approved these changes

2023-01-13 10:34 UTC, merged