Headerbar: code style fixes
elementary/code pull request #1224
Opened 2023-01-10 20:07 UTC by danirabbit

Review with "hide whitespace changes"

* Inline namespace
* Scope down permission to toolbar items
* Use box instead of grid
* Code style

2023-01-12 12:34 UTC, jeremypw requested changes
Just a few small comments inline otherwise looks good.

2023-01-12 12:34 UTC, jeremypw commented on src/Widgets/HeaderBar.vala
> +    public Gtk.Menu share_menu { get; private set; }
I think these can all be `{ get; construct; }` . Compiles and runs if this change is made.

2023-01-12 12:34 UTC, jeremypw commented on src/Widgets/HeaderBar.vala
> +        share_menu = new Gtk.Menu ();
`share_menu`  and `share_app_menu` were introduced in 2013 but seems to have never been used.

2023-01-12 12:34 UTC, jeremypw commented on src/Widgets/HeaderBar.vala
> +*           2017–2022 elementary, Inc. <https://elementary.io>
should be 2023?

2023-01-12 21:25 UTC, danirabbit commented on src/Widgets/HeaderBar.vala
> +    public Gtk.Menu share_menu { get; private set; }
None of these are constructor properties though, we don't currently pass any arguments into the constructor

2023-01-12 21:56 UTC, Marukesu commented on src/Widgets/HeaderBar.vala
> +        share_menu = new Gtk.Menu ();
IIRC, they are used by the pastebin plugin.

2023-01-13 10:06 UTC, jeremypw commented on src/Widgets/HeaderBar.vala
> +        share_menu = new Gtk.Menu ();
Your right.  I did a global search for `share_app_menu` but not `share_menu` :disappointed:

2023-01-13 10:08 UTC, jeremypw commented on src/Widgets/HeaderBar.vala
> +    public Gtk.Menu share_menu { get; private set; }
Maybe I have misunderstood `constructor property` then.  I use it to mean something initialised in the constructor which is intended to be immutable.

2023-01-13 11:30 UTC, jeremypw commented
@danirabbit Conflicts need resolving.

2023-01-13 16:58 UTC, danirabbit commented
Closing since headerbar is moving around a lot right now

2023-01-13 16:58 UTC, closed without merging