Ask save location with dialog
elementary/code pull request #1308
Opened 2023-04-11 19:29 UTC by jeremypw

Speculative PR investigating possibility of replacing the infobar (with limited layout possibilities) with a dialog when it comes to dealing with problems saving to the current location.

Because of the focus changes caused by the dialog (which trigger handlers in document) several other significant changes were needed, principally giving the document a "locked" state in which it cannot be saved or autosaved and does not react to focus changes nor is saved when closed.  The document enters this state (shown as a lock in the tab) whenever it cannot be saved to the current location and before the dialog is shown.  The document remains in that state until "save as" is performed.

In principal the document could become writable due to external changes while in a locked state but that case is not (yet) addressed.

It needs to be decided if the more intrusive dialog is a better option.

2023-04-25 01:01 UTC, danirabbit requested changes
Left a few comments. This seems to work well, nice job!

2023-04-25 16:26 UTC, jeremypw commented on src/Services/Document.vala
> +                primary_text = _("The changes to the document cannot be saved");
It was so I could distinguish which part of the code was causing the dialog to show.  You are probably right that from a user point of view there is no difference. I'll remove the distinction before merging.

2023-04-25 17:05 UTC, jeremypw commented on src/Dialogs/AskSaveLocationDialog.vala
> +        image_icon = new ThemedIcon ("dialog-warning");
Done

2023-04-25 17:16 UTC, jeremypw commented
@danirabbit Thanks for the review comments! I have actioned most of them.  There are couple that require further discussion.

2023-04-25 19:34 UTC, danirabbit commented on src/Services/Document.vala
> +                return _("Cannot save this document to %s").printf (Scratch.Utils.replace_home_with_tilde (file.get_path ()));
Naw DynamicNotebook is gone in Gtk4 anyways so wouldn't make sense to open a new issue

2023-04-25 19:59 UTC, danirabbit commented on src/Services/Document.vala
> +                    }
This seems excessive and makes Code crash if you close the window with the escape key. Probably can just be:
```suggestion
                    if (id == Gtk.ResponseType.ACCEPT) {
                        save_as_with_hold.begin ((obj, res) => {
                            if (save_as_with_hold.end (res)) {
                                locked = false;
                            }
                        });
                    }
```

2023-04-25 19:59 UTC, danirabbit commented on src/Services/Document.vala
> +                _("“%s” can't be saved here. Save a duplicate somewhere else?").printf (file.get_path ()),
Seems like this should be

```suggestion
                _("“%s” can't be saved here. Save a duplicate somewhere else?").printf (file.get_basename ()),
```

2023-04-25 19:59 UTC, danirabbit commented on src/Dialogs/AskSaveLocationDialog.vala
> +public class Scratch.Dialogs.AskSaveLocationDialog : Granite.MessageDialog {
That makes sense, but `ask_save_location ()` is already an abstraction for this dialog so to add another layer of abstraction here seems like we're creating lasagna and we should have one or the other

2023-04-26 07:39 UTC, jeremypw commented on src/Services/Document.vala
> +                    }
Yes - `assert_not_reached ()` should not really be used in released code. I put it in so any unhandled code paths are obvious when testing - and you have found one.  Will fix.

2023-04-26 07:40 UTC, jeremypw commented on src/Services/Document.vala
> +                _("“%s” can't be saved here. Save a duplicate somewhere else?").printf (file.get_path ()),
I think there was a user complaint that the basename was not sufficient - will check back.

2023-04-26 07:44 UTC, jeremypw commented on src/Dialogs/AskSaveLocationDialog.vala
> +public class Scratch.Dialogs.AskSaveLocationDialog : Granite.MessageDialog {
OK, will merge these one way or another.

2023-04-26 16:33 UTC, jeremypw commented on src/Services/Document.vala
> +                _("“%s” can't be saved here. Save a duplicate somewhere else?").printf (file.get_path ()),
I was thinking of https://github.com/elementary/files/issues/2164 when I made this change.  Not exactly the same issue but related I think.

2023-04-26 16:34 UTC, jeremypw commented on src/Services/Document.vala
> +                _("“%s” can't be saved here. Save a duplicate somewhere else?").printf (file.get_path ()),
I removed the "Save duplicate here?" text to re-shorten the prompt as it seems to repeat the text on the button.  Alternatively it could be put on a separate line?

2023-04-26 17:15 UTC, jeremypw commented on src/Services/Document.vala
> +                _("“%s” can't be saved here. Save a duplicate somewhere else?").printf (file.get_path ()),
Actually, the full path is given in the secondary text anyway so you are right the primary should just show the basename.

2023-04-26 17:17 UTC, jeremypw commented
I have now inlined the new dialog and made the other requested changes.  Also fixed some new critical warnings on startup.

2023-04-26 21:28 UTC, danirabbit approved these changes
Looks good and works as far as I can tell!

2023-04-26 21:28 UTC, merged

2023-04-26 22:13 UTC, TomiOhl commented on src/Services/Document.vala
> +                    var details = _("File “%s” was does not have write permission.");
Bit late to the party but this sentence should probably be rephrased

2023-04-27 12:31 UTC, jeremypw commented on src/Services/Document.vala
> +                    var details = _("File “%s” was does not have write permission.");
Oops! Thanks for noticing.