Add command-line "Go-To-Line" option
elementary/code pull request #1382
Opened 2023-11-24 22:41 UTC by colinkiama

Fixes #415

2023-11-26 15:00 UTC, jeremypw commented
@colinkiama Just a hint - for a substantial PR, if it is ready for review then its best to request a review either from a specific person or from the elementary/desktop-developers team (if you are able to do that).

2023-11-26 15:12 UTC, jeremypw commented
Just had a quick try of this - the commandline handling seems to work but the actual selecting and displaying the specified range does not seem to work yet? Maybe convert to draft if you are still working on this.

2023-11-26 15:14 UTC, colinkiama commented
> @colinkiama Just a hint - for a substantial PR, if it is ready for review then its best to request a review either from a specific person or from the elementary/desktop-developers team (if you are able to do that).

I don't have the option to request a reviewer on this PR sadly:
![Screenshot from 2023-11-26 15 12 19](https://github.com/elementary/code/assets/16501024/96f29678-60c6-4a4e-96ad-a1b392b93fe3)

2023-11-26 15:16 UTC, colinkiama commented
> Just had a quick try of this - the command line handling seems to work but the actual selecting and displaying the specified range does not seem to work yet? Maybe convert to draft if you are still working on this.

I'm sure that I completed this. Do you mind sharing what you wrote in the terminal to try out this feature?

2023-11-27 12:00 UTC, jeremypw commented
> > @colinkiama Just a hint - for a substantial PR, if it is ready for review then its best to request a review either from a specific person or from the elementary/desktop-developers team (if you are able to do that).
> 
> I don't have the option to request a reviewer on this PR sadly

Ah, I guess you have to be given that permission by @danirabbit . If you contribute regularly (which you seem to be doing) then that should not be a problem :smile:

2023-11-27 12:09 UTC, jeremypw commented
> > Just had a quick try of this - the command line handling seems to work but the actual selecting and displaying the specified range does not seem to work yet? Maybe convert to draft if you are still working on this.
> 
> I'm sure that I completed this. Do you mind sharing what you wrote in the terminal to try out this feature?

Strange - just tried it again and it worked this time. Not sure what happened before - I'll do some more testing and review the coding.

2023-11-27 12:31 UTC, jeremypw commented on src/Services/LocationJumpManager.vala
> +            string str = match_info.fetch_named (match_name);
```suggestion
            var str = match_info.fetch_named (match_name);
```

2023-11-27 12:34 UTC, jeremypw commented on src/Services/LocationJumpManager.vala
> +            if (int.try_parse (str, out num)) {
Theoretically `str` could be null as `fetch_named` returns `string?` according to https://valadoc.org/glib-2.0/GLib.MatchInfo.fetch_named.html.  But `try_parse` expects `string` according to https://valadoc.org/glib-2.0/int.try_parse.html so do we need to null check here?

2023-11-27 12:42 UTC, jeremypw commented on src/Services/LocationJumpManager.vala
> +namespace Scratch {
Header needed for this file.  The latest style of header we use is something like:
```
/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: 2023 elementary, Inc. <https://elementary.io>
 */
```
You may want to add an "Author" detail line as well.

2023-11-27 13:02 UTC, jeremypw commented on src/Widgets/DocumentView.vala
> +
Can this function be combined with the original `open_document` function? There is a lot of repeated code here.

2023-11-27 18:39 UTC, colinkiama commented on src/Services/LocationJumpManager.vala
> +            if (int.try_parse (str, out num)) {
While it seems to behave fine the way it is, I'll add a null check anyway just to be safe.

2023-11-27 18:57 UTC, colinkiama commented on src/Widgets/DocumentView.vala
> +
Sure!

2023-11-28 11:10 UTC, jeremypw requested changes
Just a couple of elementaryos code-style suggestions and one suggestion to avoid unnecessary multiple function returns.  Should be ready then.

2023-11-28 11:10 UTC, jeremypw commented on src/Services/LocationJumpManager.vala
> +            return num;
```suggestion
            if (str != null) {
                int.try_parse (str, out num);
            }

            return num;
```

2023-11-28 11:10 UTC, jeremypw commented on src/Application.vala
> +
```suggestion
```

2023-11-28 11:10 UTC, jeremypw commented on src/Widgets/SourceView.vala
> +            Gtk.TextIter start_iter;
```suggestion
            }
 
            Gtk.TextIter start_iter;
```

2023-11-28 14:20 UTC, colinkiama commented on src/Application.vala
> +
Done

2023-11-28 14:20 UTC, colinkiama commented on src/Widgets/SourceView.vala
> +            Gtk.TextIter start_iter;
Done

2023-11-28 15:57 UTC, jeremypw approved these changes
Good to go now,  thanks for your work!

2023-11-28 15:57 UTC, merged