Save and restore terminal pane state
elementary/code pull request #1401
Opened 2024-01-11 17:07 UTC by jeremypw

Fixes #283 

Now the terminal pane is a first -class citizen, not a plugin, it should behave like the sidebar and outline panes regarding saving and restoring its state.

2024-01-11 21:40 UTC, colinkiama commented
I'm not sure what's going on, I keep getting this error (even though I've installed the latest settings schema):

```bash
(io.elementary.code:7636): GLib-GIO-ERROR **: 21:37:17.074: Settings schema 'io.elementary.code.saved-state' does not contain a key named 'terminal-visible'
Trace/breakpoint trap
```

Can you let me know the steps to updating the settings schema? Maybe I'm missing something.

2024-01-12 10:37 UTC, jeremypw commented
> Can you let me know the steps to updating the settings schema? Maybe I'm missing something.

You should only need to install this PR (`sudo ninja install`) - the installation script compiles the schemas.  You should see at the end of the installation output in the terminal:
```
Running custom install script '/usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas'
```

2024-01-12 11:06 UTC, colinkiama commented
I did what you said above and see the same custom install script output in the terminal.

However, I still see the same error

2024-01-12 13:53 UTC, jeremypw commented
@colinkiama That's puzzling.  You are compiling with `meson build --prefix=/usr`?  Are you running `./src/io.elementary/code` or `io.elementary.code`?  If you use `dconf-editor` to look at the saved-state schema is the `terminal-visible` there and associated with a schema?  I can only get this error if I install `master` and the try to run this PR without installing it.

2024-01-12 17:15 UTC, colinkiama commented
> You are compiling with meson build --prefix=/usr?

Yes

> Are you running ./src/io.elementary/code or io.elementary.code?

Normally I run `io.elementary.code` but I tried both and still saw the same error

> If you use dconf-editor to look at the saved-state schema is the terminal-visible there and associated with a schema

![Screenshot from 2024-01-12 17 13 59](https://github.com/elementary/code/assets/16501024/e26d7f54-932a-4ad8-abfd-5e1d7e57b74c)

`terminal-visible` isn't present here.

2024-01-12 17:20 UTC, colinkiama commented
Here's the installation output and attempt to run app:

```bash
colinkiama@StarBook-mune:~/Projects/elementary-code/build$ sudo ninja install
[0/1] Installing files.
Installing data/io.elementary.code.desktop to /usr/share/applications
Installing data/io.elementary.code.metainfo.xml to /usr/share/metainfo
Installing data/io.elementary.code.policy to /usr/share/polkit-1/actions
Installing src/io.elementary.code to /usr/bin
Installing src/libcodecore.so.0.0 to /usr/lib/x86_64-linux-gnu
Installing symlink pointing to libcodecore.so.0.0 to /usr/lib/x86_64-linux-gnu/libcodecore.so.0
Installing symlink pointing to libcodecore.so.0 to /usr/lib/x86_64-linux-gnu/libcodecore.so
Installing src/codecore.h to /usr/include
Installing src/codecore.vapi to /usr/share/vala/vapi
Installing plugins/brackets-completion/libbrackets-completion.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/brackets-completion
Installing plugins/brackets-completion/brackets-completion.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/brackets-completion
Installing plugins/detect-indent/libdetect-indent.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/detect-indent
Installing plugins/detect-indent/detect-indent.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/detect-indent
Installing plugins/editorconfig/libeditorconfig.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/editorconfig
Installing plugins/editorconfig/editorconfig.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/editorconfig
Installing plugins/highlight-word-selection/libhighlight-word-selection.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/highlight-word-selection
Installing plugins/highlight-word-selection/highlight-word-selection.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/highlight-word-selection
Installing plugins/markdown-actions/libmarkdown-actions.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/markdown-actions
Installing plugins/markdown-actions/markdown-actions.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/markdown-actions
Installing plugins/pastebin/libpastebin.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/pastebin
Installing plugins/pastebin/pastebin.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/pastebin
Installing plugins/preserve-indent/libpreserve-indent.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/preserve-indent
Installing plugins/preserve-indent/preserve-indent.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/preserve-indent
Installing plugins/spell/libspell.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/spell
Installing plugins/spell/spell.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/spell
Installing plugins/vim-emulation/libvim-emulation.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/vim-emulation
Installing plugins/vim-emulation/vim-emulation.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/vim-emulation
Installing plugins/word-completion/libword-completion.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/word-completion
Installing plugins/word-completion/word-completion.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/word-completion
Installing plugins/fuzzy-search/libfuzzy-search.so to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/fuzzy-search
Installing plugins/fuzzy-search/fuzzy-search.plugin to /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/fuzzy-search
Installing po/ae/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ae/LC_MESSAGES
Installing po/af/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/af/LC_MESSAGES
Installing po/ak/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ak/LC_MESSAGES
Installing po/am/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/am/LC_MESSAGES
Installing po/ar/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ar/LC_MESSAGES
Installing po/as/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/as/LC_MESSAGES
Installing po/ast/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ast/LC_MESSAGES
Installing po/av/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/av/LC_MESSAGES
Installing po/ay/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ay/LC_MESSAGES
Installing po/az/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/az/LC_MESSAGES
Installing po/ba/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ba/LC_MESSAGES
Installing po/be/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/be/LC_MESSAGES
Installing po/bg/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/bg/LC_MESSAGES
Installing po/bh/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/bh/LC_MESSAGES
Installing po/bi/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/bi/LC_MESSAGES
Installing po/bm/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/bm/LC_MESSAGES
Installing po/bn/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/bn/LC_MESSAGES
Installing po/bo/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/bo/LC_MESSAGES
Installing po/br/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/br/LC_MESSAGES
Installing po/bs/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/bs/LC_MESSAGES
Installing po/ca/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ca/LC_MESSAGES
Installing po/ce/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ce/LC_MESSAGES
Installing po/ch/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ch/LC_MESSAGES
Installing po/ckb/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ckb/LC_MESSAGES
Installing po/co/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/co/LC_MESSAGES
Installing po/cr/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/cr/LC_MESSAGES
Installing po/cs/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/cs/LC_MESSAGES
Installing po/cu/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/cu/LC_MESSAGES
Installing po/cv/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/cv/LC_MESSAGES
Installing po/cy/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/cy/LC_MESSAGES
Installing po/da/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/da/LC_MESSAGES
Installing po/de/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/de/LC_MESSAGES
Installing po/dv/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/dv/LC_MESSAGES
Installing po/dz/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/dz/LC_MESSAGES
Installing po/ee/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ee/LC_MESSAGES
Installing po/el/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/el/LC_MESSAGES
Installing po/en_AU/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/en_AU/LC_MESSAGES
Installing po/en_CA/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/en_CA/LC_MESSAGES
Installing po/en_GB/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/en_GB/LC_MESSAGES
Installing po/eo/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/eo/LC_MESSAGES
Installing po/es/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/es/LC_MESSAGES
Installing po/et/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/et/LC_MESSAGES
Installing po/eu/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/eu/LC_MESSAGES
Installing po/fa/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/fa/LC_MESSAGES
Installing po/ff/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/ff/LC_MESSAGES
Installing po/fi/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/fi/LC_MESSAGES
Installing po/fj/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/fj/LC_MESSAGES
Installing po/fo/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/fo/LC_MESSAGES
Installing po/fr/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/fr/LC_MESSAGES
Installing po/fr_CA/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/fr_CA/LC_MESSAGES
Installing po/fy/LC_MESSAGES/io.elementary.code.mo to /usr/share/locale/fy/LC_M [...]

2024-01-12 18:40 UTC, jeremypw commented
@colinkiama Weird! I cannot see the difference between my install output and mine yet the key is not installed (or compiled) in your case.  Could you check the `data/io.elementary.code.gschema.xml` file in the project to make sure it hasn't been accidentally changed?   Next, after installing the PR, look in `/usr/share/glib-2.0/schemas` and find the installed `io.elementary.code.gschema.xml` . Open it in Code and check the 'terminal-visible' key is there.  The run `sudo /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas` manually and see if there are any errors preventing the new schema getting installed.  If you havent already try rebooting in case your system is in some weird state.

2024-01-12 19:29 UTC, colinkiama commented
Okay I resolved the problem. The issue was that I had installed elementary Code without the "/usr" prefix before. I uninstalled the app when it was built without the "/usr" prefix but the schemas in the `/usr/local/glib-2.0/schemas` were not recompiled.

So I compiled the schemas in `/usr/local/glib-2.0/schemas` then  proceeded to follow the build and installation instructions from the README file. Everything works fine now! :D

I suspect that the app was trying to load schemas from `/usr/local/glib-2.0/schemas` instead of `/usr/glib-2.0/schemas`.

2024-01-12 19:44 UTC, jeremypw commented
Ah. When I started I had similar confusions with things installed in `/usr/local`  (the default for meson) too - they take precedence over `/usr` so you have to delete them if not wanted.

2024-01-12 19:45 UTC, colinkiama requested changes
A few typos to fix.

Also, there is still some old terminal button tooltip code is still in `src/Widgets/HeaderBar.vala`

2024-01-12 19:45 UTC, colinkiama commented on src/MainWindow.vala
> +
```suggestion
                    break;
                case ACTION_TOGGLE_TERMINAL:
                    if (new_state) {
                        toolbar.terminal_button.tooltip_markup = Granite.markup_accel_tooltip (
                            app.get_accels_for_action (ACTION_PREFIX + name),
                            _("Hide Terminal")
                        );
                    } else {
                        toolbar.terminal_button.tooltip_markup = Granite.markup_accel_tooltip (
                            app.get_accels_for_action (ACTION_PREFIX + name),
                            _("Show Terminal")
                        );
                    }
```

2024-01-12 19:47 UTC, jeremypw commented
Thanks for spotting that!

2024-01-12 19:48 UTC, colinkiama commented on src/MainWindow.vala
> +
Also, is the header bar's menu button popover supposed to close when the terminal is toggled off? If not? can this be fixed?

2024-01-12 19:56 UTC, jeremypw commented on src/MainWindow.vala
> +
No - it doesn't with the other pane buttons so terminal should be the same, allthough this occurred in master too not caused by this PR.

2024-01-12 20:12 UTC, jeremypw commented
The terminal pane button issue is caused by the `current_document.grab_focus ()` being called when it closes (presumably because the terminal grabs focus when it opens). However, this seem unnecessary since the desired focus widget is unpredictable when it closes anyway.

2024-01-12 20:38 UTC, jeremypw commented
I decided to continue having the document grab focus when the terminal closes else the focus can end up on a headerbar button or somewhere unexpected.  The closing of the appmenu popover is an unfortunate side-effect but is tricky to fix and doesn't seem worth it.

2024-01-12 20:41 UTC, jeremypw commented
While here I've corrected the code which causes the terminal to grab focus.

2024-01-12 20:48 UTC, colinkiama approved these changes

2024-01-12 20:48 UTC, colinkiama commented
lgtm

2024-01-12 20:49 UTC, merged