[Feature]Implement "open-in-terminal" action
elementary/code pull request #1405
Opened 2024-01-15 17:21 UTC by jeremypw

Fixes #600 

 - Add menuitem to project folder item to open in terminal pane
 - Add hot-key for action
 - Trigger action on manual project change if terminal is visible

2024-01-15 22:38 UTC, colinkiama requested changes

2024-01-15 22:38 UTC, colinkiama commented on src/FolderManager/ProjectFolderItem.vala
> +
This is great! Just one more thing. Add an `Granite.AccelLabel` to this menu item.

The keyboard shortcut for the "Open In Terminal" action isn't discoverable otherwise.

2024-01-17 14:33 UTC, colinkiama requested changes
Just need to fix these small code style issues then it's all good!

2024-01-17 14:33 UTC, colinkiama commented on src/FolderManager/FileItem.vala
> +            };
```suggestion
            };

```

2024-01-17 14:33 UTC, colinkiama commented on src/FolderManager/ProjectFolderItem.vala
> +            );
```suggestion
            );

```

2024-01-17 14:33 UTC, colinkiama commented on src/FolderManager/ProjectFolderItem.vala
> +            };
```suggestion
            };

```

2024-01-17 17:33 UTC, jeremypw commented on src/FolderManager/ProjectFolderItem.vala
> +            );
I don't think elementary code-style requires a blank line after a statement - even multi-line ones? They are only mandated after `if {}` and other blocks that do not end in `;`

2024-01-17 17:35 UTC, jeremypw commented
@colinkiama I have questioned those style changes.  It is usual for statements that relate to the same object not to be separated by blank lines, I think.

2024-01-17 17:59 UTC, colinkiama approved these changes

2024-01-17 18:00 UTC, merged

2024-01-17 18:48 UTC, jeremypw commented
@colinkiama Well, I could be wrong - I was going on what I've seen Danielle do in her recent PRs.  But yes, clarification of docs would be good.

2024-01-17 18:53 UTC, jeremypw commented
@colinkiama Looking at the docs it says that an empty line should follow a line consisting of `}` or `)` but in this case the line consists of `};` so strictly speaking the rule does not apply.  Could be clearer though.