Store relative file paths for fuzzy finder in sets
elementary/code pull request #1420
Opened 2024-01-25 20:37 UTC by colinkiama

Fixes #1418

2024-01-26 11:41 UTC, jeremypw commented on plugins/fuzzy-search/fuzzy-finder.vala
> +                  return results;
Never reached because of `!cancellable.is_cancelled ()` in previous line?

2024-01-26 12:01 UTC, colinkiama commented on plugins/fuzzy-search/fuzzy-finder.vala
> +                  return results;
Thanks for catching that! Should be fixed now

2024-01-26 12:13 UTC, jeremypw requested changes
Everything seems to work as before except no duplicates could be created - good work. Just an inline comment.  Also there are several places where `var` should be used as the variable type is implicit.

Some searches do not work as desired but the same in master - we need to iterate on the logic some more to get searched like `code/fuzfind` to work as expected from the comment in the code (in a future PR).

2024-01-26 12:21 UTC, colinkiama commented
Sorry, I'm not sure what needs to be changed. Is it that I should use `var` instead of `Gee.Iterator` explicitly?

2024-01-26 12:38 UTC, jeremypw requested changes
I have marked where I think `var` can be used.  These are where the type can be inferred from the syntax or the `.vapi`. Usually when there is an assignment as well as a declaration.  If anything doesnt compile just revert to explicit.

2024-01-26 12:38 UTC, jeremypw commented on plugins/fuzzy-search/fuzzy-finder.vala
> +              string path = iter.get ();
Use var

2024-01-26 12:38 UTC, jeremypw commented on plugins/fuzzy-search/fuzzy-finder.vala
> +              string project_name = "";
Use var.

2024-01-26 12:38 UTC, jeremypw commented on plugins/fuzzy-search/fuzzy-finder.vala
> +                  string filename = Path.get_basename (path);
Use var

2024-01-26 12:38 UTC, jeremypw commented on plugins/fuzzy-search/fuzzy-search-project.vala
> +        Gee.Iterator<string> iter = relative_file_paths.iterator ();
Use var.

2024-01-26 12:38 UTC, jeremypw commented on plugins/fuzzy-search/fuzzy-search-project.vala
> +          string relative_path = iter.get ();
Use var.

2024-01-26 12:38 UTC, jeremypw commented on plugins/fuzzy-search/fuzzy-finder.vala
> +            Gee.Iterator<string> iter = project.relative_file_paths.iterator ();
Use var.

2024-01-26 14:01 UTC, colinkiama commented on plugins/fuzzy-search/fuzzy-finder.vala
> +            Gee.Iterator<string> iter = project.relative_file_paths.iterator ();
Updated all of these lines now

2024-01-28 10:06 UTC, jeremypw approved these changes

2024-01-28 10:08 UTC, merged