Put branch name on separate line
elementary/code pull request #1423
Opened 2024-02-22 11:10 UTC by jeremypw

Fixes #574 

Makes current branch visible without excessive sidebar width when both project and branch have long names
![Screenshot from 2024-02-22 11 03 04](https://github.com/elementary/code/assets/10513844/64de1a03-ac85-42f0-bcef-f34b3d2b24a8)

2024-02-22 19:43 UTC, zeebok approved these changes
Code looks good. Is this something that needs to be run by UX?

2024-03-12 17:22 UTC, danirabbit requested changes
I think the newline for the branch name makes sense here, but I'm -1 on making the project name even larger

2024-03-12 19:51 UTC, jeremypw commented
I find it useful to have the project names more prominent and easily readable but maybe I need new glasses ...

2024-03-13 19:47 UTC, jeremypw commented
I have left this project name size slightly increased  as it was smaller than the file items before (!).  I really think it needs to stand out at least a little.  This is how it looks now:
![Screenshot from 2024-03-13 19 45 53](https://github.com/elementary/code/assets/10513844/166ef5b4-9cd1-41ac-8a08-04d7b1f16306)

2024-03-13 22:16 UTC, danirabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                    markup = "<span size='medium'>%s</span>\n<span size='small' weight='normal'>%s</span>".printf (
I don't think the `span` is needed here :p 
```suggestion
                    markup = "%s\n<span size='small' weight='normal'>%s</span>".printf (
```

2024-03-13 22:20 UTC, danirabbit commented on src/FolderManager/ProjectFolderItem.vala
>                  } else { //Distinguish detached heads visually
don't forget to add newline to the line below this also

2024-03-14 17:51 UTC, jeremypw commented on src/FolderManager/ProjectFolderItem.vala
> +                    markup = "<span size='medium'>%s</span>\n<span size='small' weight='normal'>%s</span>".printf (
Its not larger than the folder names which was my point, although it is bold.  I would prefer it more prominent myself but in the interest of getting something merged I'll take your suggestion.

2024-03-14 19:44 UTC, danirabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                    markup = "<span size='medium'>%s</span>\n<span size='small' weight='normal'>%s</span>".printf (
If sidebar headers need to be adjusted this should be done in the platform stylesheet

2024-03-14 19:45 UTC, danirabbit approved these changes

2024-03-14 19:45 UTC, merged