WIP: [GTK4 Prep] Update DocumentView to use Hdy.TabView
elementary/code pull request #1424
Opened 2024-02-29 03:28 UTC by colinkiama

DocumentView widget has been rewritten to use the `Hdy.TabView` widget. 

The majority of the work is done. There are a few more things that left to do but I haven't figured out how to do these yet (Any help would be very appreciated!):
- [ ] Fix issue of pending save "asterisk" symbol not appearing in tabs
- [ ] Add "Open in a New Window" menu option to tab view in DocumentView.
- [ ] Support opening drag and drop operations with tabs
  - [ ] Drag tab out of window to open tab in new window
  - [ ] Drag tab into window to add tab to move tab from one window to another
 - [ ] Fix issue of visual artifacts appearing when adding/removing tabs

Part of #1157

2024-02-29 17:38 UTC, jeremypw reviewed
Just a few initial comment from looking at the code.

2024-02-29 17:38 UTC, jeremypw commented on src/Services/Document.vala
> +        private bool _loading = false;
Do we need this private variable? Can we not just return `tab.page` (or false if `tab` is null).  Can `loading` be replaced entirely with `tab.working` inline?

2024-02-29 17:38 UTC, jeremypw commented on src/Services/Document.vala
> +         public string tab_name {
Do we need both `tab_name` and `title`?

2024-02-29 17:38 UTC, jeremypw commented on src/Widgets/DocumentView.vala
> +    public Services.Document search_for_document_in_tab (Hdy.TabPage tab) {
I don't understand what this does I'm afraid.  Can't we just get the document from the child of the `TabPage` parameter?

2024-02-29 18:25 UTC, colinkiama commented on src/Services/Document.vala
> +        private bool _loading = false;
You're right, the private variable doesn't need to be there

2024-02-29 18:32 UTC, colinkiama commented on src/Services/Document.vala
> +         public string tab_name {
Nope. It's possible to just use `title`

2024-02-29 19:03 UTC, colinkiama commented on src/Widgets/DocumentView.vala
> +    public Services.Document search_for_document_in_tab (Hdy.TabPage tab) {
We can get the document from the child of the `TabPage` instead. `search_for_document_in_tab` was a supposed to be a temporary workaround for issues I had when I started working on this pull request.

2024-03-14 08:38 UTC, colinkiama commented on src/Services/Document.vala
> +         public string tab_name {
Only `title` is used now

2024-03-14 08:39 UTC, colinkiama commented on src/Services/Document.vala
> +        private bool _loading = false;
Private `_loading` variable is gone now

2024-03-24 18:55 UTC, jeremypw requested changes
Thanks for working on this. It mostly works now, just a couple of things I notice:
1) The tab background colour does not follow the "solarized light" theme (unlike `main`).  
2) The `tab_history` button is not connected up.  This button does not seem to be working in `main` either but if we are going to add it again here we might as well have it working.

2024-03-29 17:09 UTC, colinkiama commented
I've addressed the additional feedback you had.

2024-05-17 13:23 UTC, colinkiama commented
@jeremypw pinging because it has been a while

2024-05-28 18:27 UTC, danirabbit requested changes
Looks like we're missing a couple of accelerators that are present in Files:

![Screenshot from 2024-05-28 11 23 55](https://github.com/elementary/code/assets/7277719/e247f965-9b24-4a5b-a5b6-b078a1700b14)


Otherwise this looks and works good to me!

2024-05-28 18:27 UTC, danirabbit commented on src/Widgets/DocumentView.vala
> +        menu.append_section (null, open_tab_section);
It looks like these sections are the other way around in Files:

![Screenshot from 2024-05-28 11 23 55](https://github.com/elementary/code/assets/7277719/fff70dde-5fa5-4b02-921f-27458ee40d98)
![Screenshot from 2024-05-28 11 24 08](https://github.com/elementary/code/assets/7277719/98c6884f-7ee2-4c5d-bc19-0229b21dd1f2)

2024-05-28 18:27 UTC, danirabbit commented on src/Widgets/DocumentView.vala
> +        open_tab_section.append (_("Duplicate"), MainWindow.ACTION_PREFIX + MainWindow.ACTION_DUPLICATE_TAB);
This is "Duplicate Tab" in Files. Should be consistent :)
```suggestion
        open_tab_section.append (_("Duplicate Tab"), MainWindow.ACTION_PREFIX + MainWindow.ACTION_DUPLICATE_TAB);
```

2024-06-14 17:54 UTC, jeremypw requested changes
Thanks  for your continued work! The theming and closed tab button issues are now fixed and accels are showing.


One remaining behavioural issue I noticed is that the "Close Other Tabs" option is disabled when the selected tab is the first one. This should be enabled whenever there are more than one tab regardless of which is selected.

I'll use this branch for a while to check for any more regressions.

2024-06-14 18:02 UTC, jeremypw commented on src/MainWindow.vala
> +            action_accelerators.set (ACTION_DUPLICATE_TAB, "<Control><Alt>t" );
This clashes with the "ACTION_TOGGLE_TERMINAL" accelerator.

2024-06-14 18:29 UTC, colinkiama commented on src/MainWindow.vala
> +            action_accelerators.set (ACTION_DUPLICATE_TAB, "<Control><Alt>t" );
I've updated the accelerator to use `CTRL + SHIFT + K`. This matches GNOME Web and Microsoft Edge. Is this okay?

2024-06-15 15:46 UTC, jeremypw commented
Requesting review from @danirabbit regarding what accels to use consistently for tab menu between Code, Files, Terminal and Web (if they need to be consistent).

2024-06-15 15:51 UTC, danirabbit commented
Looks like Chrome and Edge are also using "Ctrl Shift K". Safari uses Super Shift K. So it makes sense for us to be in line with what appears to be a de facto standard here. We should probably add this shortcut to Files too

2024-06-15 17:44 UTC, jeremypw commented
OK, I'll leave it as is here and modify Files and Terminal to match.

2024-06-15 17:44 UTC, jeremypw approved these changes

2024-06-15 18:44 UTC, danirabbit approved these changes
Let's go! :rocket:

2024-06-15 18:44 UTC, merged

2024-06-19 19:04 UTC, jeremypw commented
Just found another regression - dropping a file from Files onto the tabbar (empty space) no longer opens it in a new tab.  @colinkiama   Would you like to submit a new PR fixing that? If not I'll try to fix it some time.

2024-06-19 21:34 UTC, colinkiama commented
I won't be working on this until next week. Feel free to fix this in the meantime.

2024-06-20 16:35 UTC, jeremypw commented
@colinkiama I could not get dropping onto the empty tabbar space to work in my Terminal branch https://github.com/elementary/terminal/pull/760 - there was no obvious way to access a widget for that area. I could only implement dropping onto the add button and tab labels.  In Code, dropping onto the add button already works.  I can implement dropping onto tab labels easily enough.

2024-06-20 16:43 UTC, jeremypw commented
Before converting to Hdy.TabView, Code did not support dropping onto the tab labels, I guess because it is not clear what should happen? Should the contents of the dropped file replace the contents of the document (destructive), should it be appended to the document,  should the document be closed and a new one created from the dropped file, replacing the old document or should a new tab be created?

2024-06-20 16:46 UTC, jeremypw commented
Gedit only implements drop on the add button anyway so maybe we can just leave this (unless someone can find a way implementing drop on empty space