Define terminal menu items using GLib.MenuModel
elementary/code pull request #1438
Opened 2024-06-17 12:49 UTC by colinkiama

Replaces usage of Gtk.MenuItem with GLib.MenuModel in the Terminal widget as #1157

2024-06-17 17:13 UTC, danirabbit requested changes
Looks good and works as expected! Just a couple of comments

2024-06-17 17:13 UTC, danirabbit commented on src/Widgets/Terminal.vala
> +
extra whitespace

2024-06-17 17:13 UTC, danirabbit commented on src/Widgets/Terminal.vala
> +
Is there a reason to add new public methods here? Seems like this is simple enough we could just keep it as lambdas as before

2024-06-17 17:13 UTC, danirabbit commented on src/Widgets/Terminal.vala
> +    private SimpleAction paste_action;
Do we need to hold a reference for these actions here? It seems like they're only used in the construct method right?

2024-06-18 07:24 UTC, colinkiama commented on src/Widgets/Terminal.vala
> +
No reason. I moved the logic back in to lambdas.

2024-06-18 07:25 UTC, colinkiama commented on src/Widgets/Terminal.vala
> +    private SimpleAction paste_action;
Thanks for catching that! We don't. These have been moved to the construct block.

2024-06-18 17:19 UTC, danirabbit approved these changes
Nice work :tada:

2024-06-18 17:19 UTC, merged