[GTK4 Prep] Update FileView item context menus now created using GLib.MenuModel
elementary/code pull request #1442
Opened 2024-06-26 08:03 UTC by colinkiama

Final part of "Replace Gtk.MenuItem with GLib.MenuModel" task.

Fixes #1157

2024-06-27 17:42 UTC, danirabbit requested changes
This is a lot to review at one time. It's kind of difficult. Do you think you could break this up a bit? Maybe first a branch with some of these changes to existing actions like making the branch action stateful, a branch changing some of these classes to use actions like for example adding actions to FileView could honestly be its own branch, and then finally a branch changing things to use glib menu at the end of that? There's just so many changes here that it's hard to see what's going on and there's quite a few code style and white space errors etc

2024-06-27 17:42 UTC, danirabbit commented on src/Utils.vala
> +        }
Can you explain why you're getting all apps for a file type etc here and not just creating a new https://valadoc.org/gio-unix-2.0/GLib.DesktopAppInfo.html ?

2024-06-27 17:42 UTC, danirabbit commented on src/FolderManager/FileItem.vala
> + namespace Scratch.FolderManager {
extra space here

2024-06-27 17:42 UTC, danirabbit commented on src/FolderManager/FileItem.vala
> +            open_in_menu.append_section (null, open_in_extra_section);
This is kind of messy:
```suggestion

            var open_in_top_section = new GLib.Menu ();
            open_in_top_section.append_item (new_window_menu_item);

            var open_in_app_section = Utils.create_executable_app_items_for_file (file.file, file_type);

            var open_in_other_menu_item = new GLib.MenuItem (
                _("Other Application…"),
                GLib.Action.print_detailed_name (
                    FileView.ACTION_PREFIX + FileView.ACTION_SHOW_APP_CHOOSER,
                    file.path
                )
            );

            var open_in_extra_section = new GLib.Menu ();
            open_in_extra_section.append_item (open_in_other_menu_item);

            var open_in_menu = new GLib.Menu ();
            open_in_menu.append_section (null, open_in_top_section);
            open_in_menu.append_section (null, open_in_app_section);
            open_in_menu.append_section (null, open_in_extra_section);
```

2024-06-27 17:42 UTC, danirabbit commented on src/FolderManager/FolderItem.vala
> +                                                      + FileView.ACTION_RENAME_FOLDER);
Code style:
```suggestion
            var rename_menu_item = new GLib.MenuItem (
                _("Rename"),
                FileView.ACTION_PREFIX + FileView.ACTION_RENAME_FOLDER
            );
```

2024-06-27 17:42 UTC, danirabbit commented on src/FolderManager/ProjectFolderItem.vala
> +
extra whitespace

2024-06-27 18:35 UTC, colinkiama commented on src/Utils.vala
> +        }
Honestly, I can't remember. I did this months ago. Creating a new `DesktopAppInfo` instance is much more efficient. Not sure how I missed that.

2024-07-24 16:25 UTC, danirabbit commented
@colinkiama did you want to try to resolve conflicts here or should this be closed?

2024-07-24 16:27 UTC, colinkiama commented
This should be closed.

2024-07-24 16:51 UTC, closed without merging