[GTK4 Prep] Add FileView actions
elementary/code pull request #1444
Opened 2024-06-27 21:36 UTC by colinkiama

Adds actions to FileView to prepare to use GLib.MenuModel for context menus in FileView items. As part of #1442

2024-06-27 21:54 UTC, danirabbit requested changes
A few inline comments

It also looks like none of these actions are used at all in this branch? Gtk.MenuItem is a Gtk.Actionable so it is possible to use GLib.Actions with Gtk.MenuItem without having to also port everything to GLib.Menu in the same commit.

Really the reason I'm asking for things to be broken up in separate commits to make sure they they are not only reviewable, but so that in a possible future git blame we can track changes more easily. So if we're introducing a bunch of dead code that's not really reviewable either even though the commit is smaller and it will make it harder to traverse history

2024-06-27 21:54 UTC, danirabbit commented on src/FolderManager/FileView.vala
> +        rename_folder_action = new SimpleAction (ACTION_RENAME_FOLDER, null);
Is there a reason this is a separate SimpleAction instead of part of ActionEntries?

2024-06-27 21:54 UTC, danirabbit commented on src/FolderManager/FileView.vala
> +    public SimpleAction rename_folder_action { get; private set; }
Is there a reason for these to be public?

2024-06-27 21:54 UTC, danirabbit commented on src/FolderManager/FileView.vala
> +    public SimpleActionGroup actions { get; construct; }
`construct` should be for construction properties. It doesn't look like this is set from inside a constructor

2024-06-27 21:54 UTC, danirabbit commented on src/FolderManager/FileView.vala
> +    public const string ACTION_CHANGE_BRANCH = "change-branch";
I don't see this action here?

2024-06-27 21:55 UTC, danirabbit commented on src/FolderManager/FileView.vala
> +    public void rename_file (string path) {
Is there a reason this method is public?

2024-06-27 22:43 UTC, colinkiama commented on src/FolderManager/FileView.vala
> +    public void rename_file (string path) {
Nope

2024-06-29 19:10 UTC, colinkiama commented on src/FolderManager/FileView.vala
> +        rename_folder_action = new SimpleAction (ACTION_RENAME_FOLDER, null);
I must have thought it wasn't possible months ago for some reason. I've managed to include the action in ActionEntries now

2024-06-29 19:34 UTC, colinkiama commented on src/FolderManager/FileView.vala
> +    public SimpleAction rename_folder_action { get; private set; }
Not right now. Only one I've left as `public` is `toplevel_action_group` because it was already `public`.

2024-06-29 19:34 UTC, colinkiama commented on src/FolderManager/FileView.vala
> +    public SimpleActionGroup actions { get; construct; }
I've turned `actions` into a private field now.

2024-06-29 19:37 UTC, colinkiama commented on src/FolderManager/FileView.vala
> +    public const string ACTION_CHANGE_BRANCH = "change-branch";
I've removed it now.

2024-06-29 19:39 UTC, colinkiama commented
I've made changes that should address all your comments.

FileView actions are now used by Gtk.MenuItems in FileView items.

2024-06-30 02:49 UTC, danirabbit requested changes
Nice! Everything is working here afaict, just a few more comments

2024-06-30 02:49 UTC, danirabbit commented on src/FolderManager/FileItem.vala
> +                sensitive = view.rename_request (file)
We should set the action `enabled` property rather than setting the widget sensitivity. This will automatically set widget sensitivity but also make sure that if the action is used elsewhere we're only setting it in the one place and it affects any keyboard shortcuts too

2024-06-30 02:49 UTC, danirabbit commented on src/FolderManager/FileView.vala
> +            if (start_editing_item (folder_to_rename)) {
indentation mistake here?

2024-06-30 02:49 UTC, danirabbit commented on src/FolderManager/FileView.vala
> +            critical ("Could not find folder from given path to rename: %s", path);
return here?

2024-06-30 02:49 UTC, danirabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                sensitive = view.root.children.size > 1
Same here with sensitivity, this should be handled by setting the action sensitive when the number of children change

2024-06-30 12:25 UTC, colinkiama commented
I've now made changes to address your latest comments

2024-07-02 16:26 UTC, danirabbit reviewed
Couple more things here, but I think that's the last bit!

2024-07-02 16:26 UTC, danirabbit commented on src/FolderManager/FileView.vala
> +        project_item.close_all_except ();
It looks like this sends a signal that is connected to in this class on line #476. So perhaps that whole block of code should just live here instead of sending signals back and forth?

2024-07-02 16:26 UTC, danirabbit commented on src/FolderManager/FileView.vala
> +     private void action_delete (SimpleAction action, Variant? param) {
Extra whitespace and an indentation error?

2024-07-02 16:26 UTC, danirabbit commented on src/FolderManager/ProjectFolderItem.vala
> +            close_other_folders_action.set_enabled (view.root.children.size > 1);
This should be in `View` instead and be something like a function that is connected to `root.child_added` and `root.child_removed` and sets the action enabled state there

2024-07-02 21:58 UTC, colinkiama commented on src/FolderManager/FileView.vala
> +        project_item.close_all_except ();
This is done now

2024-07-02 21:58 UTC, colinkiama commented on src/FolderManager/FileView.vala
> +     private void action_delete (SimpleAction action, Variant? param) {
Fixed!

2024-07-02 22:24 UTC, danirabbit approved these changes
Nice job!

2024-07-02 22:25 UTC, merged