[GTK4 Prep] Move External App Actions Logic To Utils
elementary/code pull request #1455
Opened 2024-07-24 19:04 UTC by colinkiama

Part of of "Replace Gtk.MenuItem with GLib.MenuModel" task in #1157

2024-07-24 20:28 UTC, danirabbit requested changes
Seems sensible. Just one question and a couple comments about extra whitespace

2024-07-24 20:28 UTC, danirabbit commented on src/Utils.vala
> +    }
`file_type` appears to be unused here. This seems to be a duplicate of `launch_app_with_file` but just with the one liner to create a GLib.File from path. Should this function exist?

2024-07-24 20:28 UTC, danirabbit commented on src/Utils.vala
> +
extra space

2024-07-24 20:28 UTC, danirabbit commented on src/Utils.vala
> +
extra space

2024-07-24 21:11 UTC, colinkiama commented on src/Utils.vala
> +    }
No, it doesn't need to. It has been removed now

2024-07-24 21:12 UTC, colinkiama commented
I've made new changes that should resolve all the issues now.

2024-07-24 21:47 UTC, danirabbit commented on src/Utils.vala
> +            var contracts = Granite.Services.ContractorProxy.get_contracts_by_mime (file_type);
Should this be https://valadoc.org/granite-7/Granite.Services.ContractorProxy.get_contracts_for_file.html so we don't have to manually get file type?

2024-07-24 21:47 UTC, danirabbit commented on src/Utils.vala
> +            var contracts = Granite.Services.ContractorProxy.get_contracts_by_mime (file_type);
Same here

2024-07-25 08:21 UTC, colinkiama commented on src/Utils.vala
> +            var contracts = Granite.Services.ContractorProxy.get_contracts_by_mime (file_type);
Yeah. That makes the code more concise. Thanks!

2024-07-25 08:21 UTC, colinkiama commented on src/Utils.vala
> +            var contracts = Granite.Services.ContractorProxy.get_contracts_by_mime (file_type);
This has been updated now too.

2024-07-25 14:50 UTC, danirabbit approved these changes
Nice work!

2024-07-25 14:50 UTC, merged