Fix the app crashing when two folders and their ancestors have the same names
elementary/code pull request #1460
Opened 2024-08-11 16:26 UTC by aguillon

Hi!

I think this fixes https://github.com/elementary/code/issues/1440. As mentioned there, a way to reproduce is to open the folders `/usr` and `$HOME/usr`. In this case, the issue is not so much that the two folders and their ancestors have the same names, but that `find_unique_path` does not handle recursion up to the root.

This is my first contribution to a Vala project, ever. In particular, I don't know how to call a code formatter or how to write unit tests (which would make a lot of sense with the present issue). If you show me how, I will gladly update my PR.

2024-08-11 17:04 UTC, jeremypw commented
@aguillon I use `vala-lint` to flag up elementaryOS code style issues but no automatic code formatting at the moment. The CI will fail if there are serious code style errors (as it does currently).

You can get the source code of `vala-lint` from https://github.com/vala-lang/vala-lint.git.

The project does not current implement any unit tests so don't worry about that.  You can look at other projects like Files and Terminal for examples of how it is done.

I have quickly tried out your fix and it seems to be working!  I'll test it a bit more then it should be good to merge.

2024-08-11 17:15 UTC, jeremypw requested changes
This fixed a the situation mentioned in the linked issue.  As `get_parent ()` can return `null` I think you need to perform a null check before referencing that parent.

2024-08-12 14:22 UTC, aguillon commented
Thank you for `vala-lint`.

> As get_parent () can return null I think you need to perform a null check before referencing that parent.

Thank you, indeed this could happen if we add the root as a project. This should work now.

2024-08-14 16:49 UTC, jeremypw requested changes

2024-08-14 16:49 UTC, jeremypw commented on src/Utils.vala
>              f2_parent = f2_parent.get_parent ();
Should these be null checked too? These parents are referenced in the loop condition.

2024-08-18 13:12 UTC, aguillon commented on src/Utils.vala
>              f2_parent = f2_parent.get_parent ();
If both previous `has_parent` return `true`, I assume `get_parent` cannot return `null`, no?

2024-08-18 17:09 UTC, jeremypw commented on src/Utils.vala
>              f2_parent = f2_parent.get_parent ();
Ah yes, sorry.

2024-08-18 17:09 UTC, jeremypw approved these changes
Lets merge this now!

2024-08-18 17:11 UTC, merged