Migrate to libpease-2
elementary/code pull request #1501
Opened 2024-12-25 14:21 UTC by jeremypw

2024-12-25 21:37 UTC, kaixoo commented
> Needed to ship a .vapi for libpeas-2 as is not currently supplied by the libpeas-2-dev package available

Can we send this upstream?

2024-12-26 11:31 UTC, jeremypw commented
> Can we send this upstream?

Probably, it should just be a matter of deb packaging.  However, I am not convinced libpeas-2 is the way to go - it provides a lot of stuff we don't need like loading JavaScript plugins which has to be included in the Flatpak (unless there are some compile options I haven't found yet).  I am going to try to produce another PR removing libpeas altogether for comparison.

2024-12-26 11:36 UTC, jeremypw commented
Libpeas may provide small advantages in code organization, but as far as I am aware the main point is to allow third-party plugins written in other languages and separately packaged in other projects to be used (they just need to be installed into the right directory).

2024-12-26 13:53 UTC, kaixoo commented
I don't see a problem in allowing to load Javascript plugins, but okay.

2024-12-26 14:57 UTC, jeremypw commented
Its not a problem, just unnecessary.  Need to identify functional advantages of libpeas to justify the extra dependencies.

2024-12-29 16:22 UTC, jeremypw commented
@danirabbit Will it be possible to ship libpeas-2 version 2.0.5 in elementary 8 if it is not in Ubuntu 24.04?

2024-12-29 16:24 UTC, jeremypw commented
The main advantage of keeping the libpeas dependency for now is, especially if we can lose the need for the `.vapi`, is the smaller diff.

2024-12-29 17:34 UTC, jeremypw commented
Hmm - as far as I can make out,, even Gnome is not using `libpeas-2` for their `gedit` flatpak :disappointed:

2024-12-30 16:15 UTC, jeremypw commented
@leonardo-lemos Thanks!  I forgot to check the CI file as everything worked locally.

2025-01-15 19:59 UTC, kaixoo commented
@jeremypw if you need help in anything you can tell me

2025-01-16 11:41 UTC, jeremypw commented
@kaixoo Thanks for the offer. The limiting factor is getting reviews and re-reviews of existing (simpler, ready) PRs tbh.  I guess people are focussed on finalizing the stable release of OS 8.  I could mark this as ready for review if you like, otherwise I was waiting for the `.vapi` file to be included in the `-dev` package.

I've started a fork of Code that I can use myself at least that contains some of the more useful features that are not in the original.

2025-01-16 13:11 UTC, kaixoo commented
Ah, alright, I guess it's fine to wait then.

2025-05-05 02:51 UTC, leonardo-lemos commented
@jeremypw Can you resolve the conflicts here, please? I'd like to take a look at this PR ;)

2025-05-09 15:50 UTC, leonardo-lemos requested changes
Works as expected, but we need to update dependencies in the README too.

2025-05-17 17:23 UTC, leonardo-lemos approved these changes
LGTM!

2025-05-17 17:23 UTC, merged