Vim emulation: fix 0 command
elementary/code pull request #783
Opened 2020-03-20 17:44 UTC by mcclurgm

Part of splitting #633. Based on the implementation of the `I` command and gnome-builder.

Note, this does not work with selection. It simply removes the selection entirely. But as far as I can tell, the plugin does not implement selection in any way, so I don't believe this is a regression.

2021-02-06 17:42 UTC, jeremypw commented
This seems to move the cursor down a line - not to the beginning of the line (which I think is what is expected from https://devhints.io/vim).

2021-02-06 17:51 UTC, jeremypw requested changes
See inline comment

2021-02-06 17:51 UTC, jeremypw commented on plugins/vim-emulation/vim-emulation.vala
> +                    buffer.place_cursor (insert);
This can simply be `view.move_cursor (Gtk.MovementStep.DISPLAY_LINE_ENDS, -1, false);`

2021-02-07 17:04 UTC, mcclurgm commented on plugins/vim-emulation/vim-emulation.vala
> +                    buffer.place_cursor (insert);
That seems like it should, but it ignores whitespace, so it moves to after any indentation. `0` is supposed to move the the first character of the line, regardless of indentation. That's one of the issues I was trying to fix with this PR. The whitespace-respecting command is `^`.

2021-02-08 11:36 UTC, jeremypw commented on plugins/vim-emulation/vim-emulation.vala
> +                    buffer.place_cursor (insert);
Oh, yeah - sorry.  In that case you can fix it with fewer lines with:
```
                    view.move_cursor (Gtk.MovementStep.PARAGRAPH_ENDS, -1, false);
                    view.move_cursor (Gtk.MovementStep.DISPLAY_LINE_ENDS, -1, false);
```

This seems to give the same behaviour as the Vim app.

2021-02-11 03:45 UTC, mcclurgm commented on plugins/vim-emulation/vim-emulation.vala
> +                    buffer.place_cursor (insert);
Hmm, looks good in my testing. Makes sense with the docs too. That's a nice improvement, thanks!

2021-02-11 11:19 UTC, jeremypw approved these changes
Lets go!

2021-02-15 17:37 UTC, jeremypw commented
Need someone to fix the flatpak CI before this can be merged.

2021-03-24 11:24 UTC, merged