Vim emulation: add "o", "O" commands
elementary/code pull request #785
Opened 2020-03-29 03:55 UTC by mcclurgm

Implements a basic form of the `o` and `O` commands in vim. It adds a new line before or after the current, navigates to that line, and enters insert mode.

As with #712 (and the other insertion commands), this doesn't properly work with numbers. It won't repeat the insert multiple times, only once.

2021-02-06 18:17 UTC, jeremypw commented on plugins/vim-emulation/vim-emulation.vala
> +                buffer.insert (ref insert, "\n", 1);
Can't this be replaced by view.insert_at_cursor ("\n"); ?

2021-02-06 18:18 UTC, jeremypw requested changes
This works as expected but some simplification is possible.

2021-02-06 18:18 UTC, jeremypw commented on plugins/vim-emulation/vim-emulation.vala
> +                buffer.insert (ref insert, "\n", 1);
Also this.

2021-02-07 16:54 UTC, mcclurgm commented on plugins/vim-emulation/vim-emulation.vala
> +                buffer.insert (ref insert, "\n", 1);
Yep, seems to work for me. I don't think I knew about that before. Thanks!

2021-02-07 16:55 UTC, mcclurgm commented
Ok, I fixed your requests. There's one big issue remaining here that I just discovered, that the `MovementStep.PARAGRAPH_START` goes to the beginning of the line excluding whitespace. So the shift-O command needs some more work. I'll see if I can fix that.

2021-02-07 20:04 UTC, mcclurgm commented
Since the effect is pretty much the same as inserting a newline after the `0` motion, I'm going to wait until we figure that out and then follow that solution here.

2021-02-08 11:44 UTC, jeremypw commented on plugins/vim-emulation/vim-emulation.vala
> +                view.move_cursor (Gtk.MovementStep.PARAGRAPH_ENDS, -1, false);
I think you can insert `view.move_cursor (Gtk.MovementStep.DISPLAY_LINE_ENDS, -1, false);` here to ignore whitespace.

2021-02-11 03:51 UTC, mcclurgm commented
One more thought I just had. This doesn't respect the current line ending setting. I guess I'll have to fix that too…

2021-02-15 17:38 UTC, jeremypw commented
Need someone to fix the flatpak CI before this can be merged.

2021-03-24 15:35 UTC, jeremypw approved these changes

2021-03-24 15:36 UTC, jeremypw commented
I think any issues with non-standard line-endings can be dealt with, if required, later. Code is focused on code development on Linux.

2021-03-24 15:36 UTC, merged