Fix issues with the Pastebin plugin
elementary/code pull request #872
Opened 2020-09-04 02:44 UTC by sebastianlay

This fixes all of the issues mentioned in #871, removes one warning from #773 and improves the overall aesthetics of this plugin.

Before:
![before](https://user-images.githubusercontent.com/2980983/92193531-e0939800-ee68-11ea-80c0-f0e5466dcf73.png)

After:
![after](https://user-images.githubusercontent.com/2980983/92193539-e4bfb580-ee68-11ea-9e3c-c01002b021af.png)

I also adjusted some of the translatable texts in the code and I am not sure whether there is anything else needed there to make them available for translation.

2020-09-04 16:40 UTC, danrabbit requested changes
I can confirm that this branch works as expected. Really nice job with the cleanup and the fixes!

I have just a few suggestions inline. Thanks for working on this!

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +                resizable: false,
What's the reason for making this not resizable?

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            }
In general, it's better to add the provider directly to the widgets you need instead of to the whole screen. This can cause unintended consequences for other widgets in the app.

But I think it would be more in keeping with the style of other system components to put this list inside of a Gtk.Frame instead of removing its background

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            var format_button = new Gtk.Button.with_label (_("…"));
It definitely looks cleaner this way than with the label, but now it's a little inaccessible. I would suggest instead making this a `Button.with_image_from_icon_name` and using `view-more-horizontal-symbolic` for the icon. Then it will need a tooltip to remain accessible. Maybe "Other formats" or something descriptive like this

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            var expiry_combo_l = new Gtk.Label (_("Expiration:"));
Haha yep, this is definitely better

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            grid.row_spacing = 8;
For spacing we always use multiples of 3 (unless you're trying to account for some off-by-one issue). Column spacing should be 6px and row spacing should be 12px typically with double spacing (24px) between sections. So the previous values here were correct

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
>              content_area.add (stack);
If you wanted to simplify this further, we probably don't need to cache `content_area` since we don't use it again
```suggestion
            get_content_area ().add (stack);
```

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            upload_button.get_style_context ().add_class (Gtk.STYLE_CLASS_SUGGESTED_ACTION);
Nice improvement!

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            format_dialog.title = _("More formats");
Titles should probably be in Title Case
```suggestion
            format_dialog.title = _("More Formats");
```

And I guess the tooltip for the button from the other dialog should match this title. But tooltips are sentence case :)

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            languages_scrolled.margin_bottom = 10;
While we're doing all this, might as well use latest code style
```suggestion
            var languages_scrolled = new Gtk.ScrolledWindow (null, null) {
                hscrollbar_policy = Gtk.PolicyType.NEVER,
                height_request = 250,
                expand = true,
                margin = 12,
                margin_top = 0
            };
```

And a little trick since we want all sides to have even margin except the top, we can set margin and then override that one side

2020-09-04 16:40 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            content_area.add (languages_scrolled);
Same as above
```suggestion
            format_dialog.get_content_area ().add (languages_scrolled);
```

2020-09-04 19:41 UTC, sebastianlay commented on plugins/pastebin/pastebin_dialog.vala
> +                resizable: false,
I don't see the benefit here since there is no widget that would scale with the window.

2020-09-04 19:41 UTC, sebastianlay commented on plugins/pastebin/pastebin_dialog.vala
> +            }
You are right. Looks better this way, too!

2020-09-04 19:43 UTC, sebastianlay commented on plugins/pastebin/pastebin_dialog.vala
> +            var format_button = new Gtk.Button.with_label (_("…"));
I replaced it with the icon you suggested and set the "name" property on the button. That should do the trick, right?

2020-09-04 19:44 UTC, sebastianlay commented on plugins/pastebin/pastebin_dialog.vala
> +            grid.row_spacing = 8;
Good to know! I reverted the change and adjusted the other spacings to match that.

2020-09-04 19:44 UTC, sebastianlay commented on plugins/pastebin/pastebin_dialog.vala
>              content_area.add (stack);
Absolutely.

2020-09-04 19:45 UTC, sebastianlay commented on plugins/pastebin/pastebin_dialog.vala
> +            format_dialog.title = _("More formats");
Already did that in another commit.

2020-09-04 19:45 UTC, sebastianlay commented on plugins/pastebin/pastebin_dialog.vala
> +            upload_button.get_style_context ().add_class (Gtk.STYLE_CLASS_SUGGESTED_ACTION);
Thanks!

2020-09-04 20:30 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            var format_button = new Gtk.Button.with_label (_("…"));
The name property won't set a tooltip. You'll need to use the property `tooltip_text`.

2020-09-04 20:38 UTC, danrabbit requested changes
This looks great! Just the one comment about the tooltip :)

2020-09-04 20:38 UTC, danrabbit commented on plugins/pastebin/pastebin_dialog.vala
> +            format_button.name = _("Choose Different Format");
I believe this is only used internally by Gtk. You'll want to use `tooltip_text`
```suggestion
            var format_button = new Gtk.Button.from_icon_name ("view-more-horizontal-symbolic") {
                tooltip_text = _("Choose different format")
            };
```

also, tooltip labels should use Sentence case. I know it's a lot to remember :sweat_smile:

2020-09-04 22:58 UTC, sebastianlay commented on plugins/pastebin/pastebin_dialog.vala
> +            format_button.name = _("Choose Different Format");
Always learning.

2020-09-04 23:12 UTC, danrabbit approved these changes
Great work! Thank you very much :)

2020-09-04 23:12 UTC, merged

2020-09-05 12:33 UTC, sebastianlay commented on plugins/pastebin/pastebin_dialog.vala
> +                resizable: false,
Okay, but I will leave that for another time.