Add flatpak manifest
elementary/code pull request #877
Opened 2020-09-07 04:09 UTC by Marukesu

create a flatpak manifest using the gnome Sdk and elementary BaseApp.

2020-09-07 17:22 UTC, danrabbit commented
Hey thank you for submitting this PR! Do you think it would be possible to add a Flatpak build step to CI as well so that we ensure this stays functional?

2020-09-07 18:45 UTC, Marukesu commented
sure, is this sufficient ?
```yaml
  flatpak:

      runs-on: ubuntu-latest

      container:
       image: elementary/docker:unstable

      steps:
     - uses: actions/checkout@v1
     - name: Install flatpak-builder
       run: |
         apt update
         apt install -y flatpak flatpak-builder
     - name: install flathub remote and runtimes
       run: |
         flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
         flatpak install -y flathub org.gnome.Platform//3.36 org.gnome.Sdk//3.36 io.elementary.BaseApp//juno-19.08
     - name: Build flatpak manifest
       run: flatpak-builder flatpak-build --repo=flatpak-repo --force-clean --ccache flatpak-build io.elementary.code.yml
```

2020-09-08 19:03 UTC, danrabbit commented
@Marukesu As long as that builds, works for me :)

2020-09-10 01:37 UTC, Marukesu commented
added the job on CI.

2020-09-10 16:58 UTC, danrabbit requested changes

2020-09-10 16:58 UTC, danrabbit commented on io.elementary.code.yml
> +      - name: intltool
Afaict this isn't used anymore so we shouldn't need it

2020-09-10 19:02 UTC, Marukesu commented on io.elementary.code.yml
> +      - name: intltool
without it, gtkspell won't build

2020-10-02 07:57 UTC, 4jNsY6fCVqZv commented
How do you want to deal with the situation that the GNOME runtime is hosted on Flathub, but Flathub is not a FLOSS compatible solution because proprietary applications are also distributed there as well?

2020-10-20 21:45 UTC, danrabbit approved these changes
Nice job. Builds and runs locally and CI works :+1:

2020-10-20 21:45 UTC, merged