Add Markdown plugin
elementary/code pull request #890
Opened 2020-10-02 00:57 UTC by igordsm

This fixes #850 . Add a Markdown plugin with the following shortcuts:

* Ctrl+b for bold
* Ctrl+Shift+I for italic
* Ctrl+K for links

See a demo below. All three works with and without a selection (and place the cursor where it makes sense).

![PR-markdown](https://user-images.githubusercontent.com/221446/94877263-66870c80-0430-11eb-96c5-88a72b161aaf.gif)

2020-10-02 05:31 UTC, cassidyjames commented
Ah, yeah Ctrl+I is the jump-to-line feature. Hrm. @danrabbit thoughts on that?

2020-10-14 16:55 UTC, jeremypw reviewed
See inline comments - review for functionality and regressions to follow.

2020-10-14 16:55 UTC, jeremypw commented on plugins/markdown-actions/markdown-actions.vala
> +        if (control && !shift && evt.keyval == Gdk.Key.b) {
You should ideally also test for other possible shortcut modifiers:

`var other_mods = (evt.state & Gtk.accelerator_get_default_mod_mask () & ~Gdk.ModifierType.SHIFT_MASK & ~Gdk.ModifierType.CONTROL_MASK) != 0;`

and check this is false so that you know only Control and/or Shift is being pressed.

You can save some process by returning immediately if `event.is_modifier == 1` is true.

2020-10-14 16:55 UTC, jeremypw commented on plugins/markdown-actions/markdown-actions.vala
> +            current_source.notify["language"].connect (configure_shortcuts);
I am not sure this works with a proxy property - I'll check.  Probably need
`((Gtk.SourceBuffer)(current_source.buffer)).notify["language"].connect ()`

Might be worth keeping an (unowned) reference `current_buffer = (Gtk.SourceBuffer)(current_source.get_buffer ())` anyway rather than keep creating temporary references.

Does this connection need to be disconnected when doc changes?

2020-10-14 17:56 UTC, jeremypw commented
I think all the shortcuts should work with ` <Control><Shift>` otherwise its confusing whether or not you need to hold the shift key  down.

2020-10-17 16:00 UTC, jeremypw requested changes
The code works as expected and no regressions were found.  Some coding issues are mentioned inline.

2020-10-24 12:33 UTC, igordsm commented on plugins/markdown-actions/markdown-actions.vala
> +                current_source.key_press_event.disconnect (shortcut_handler);
Done.

2020-10-24 12:59 UTC, igordsm commented on plugins/markdown-actions/markdown-actions.vala
> +        if (control && !shift && evt.keyval == Gdk.Key.b) {
Done.

2020-10-24 13:01 UTC, igordsm commented on plugins/markdown-actions/markdown-actions.vala
> +        if (control && !shift && evt.keyval == Gdk.Key.b) {
Done.

2020-10-24 13:02 UTC, igordsm commented on plugins/markdown-actions/markdown-actions.vala
> +            current_source.notify["language"].connect (configure_shortcuts);
Should we change this?

2020-10-24 13:20 UTC, igordsm commented
@jeremypw Thank you for the reviews! I have addressed all but one (left a comment in the discussion above) and re-request a review. 

I actually like using `ctrl`+`shift` more, since it feels more natural to apply the markups after selecting text.

2020-10-26 16:26 UTC, jeremypw commented on plugins/markdown-actions/markdown-actions.vala
> +            current_source.notify["language"].connect (configure_shortcuts);
No, its OK.  I seem to remember in the past this wouldn't work but it seems with more recent Vala it does.

2020-10-26 16:35 UTC, jeremypw submitted a review, later dismissed

2020-10-26 16:37 UTC, jeremypw commented
Works nicely now - thank!  But you will need to add an entry to the next release in the appdata file.  I'll reinstate the review request to the ux team.

2020-10-27 17:14 UTC, igordsm commented
By the way, the Flatpak CI is returning with a very non-specific error (`Failed to download sources: module gtksourceview: Failed to execute child process ?git? (No such file or directory)`) that appears to be unrelated to the last commit. Is it supposed to work?

2020-11-21 22:18 UTC, igordsm commented
I have created a standalone repository [https://github.com/igordsm/code-markdown-plugin](https://github.com/igordsm/code-markdown-plugin) that implements this PR and installs to the correct folders in Elementary 6. 

I started a discussion on third party plugins at #908 . I would be happy to hear your @jeremypw @cassidyjames thoughts about that and to make this a third party plugin distributed via AppCenter.

2020-11-25 00:03 UTC, danrabbit requested changes
This seems to work as expected except with undo. It looks like for some reason undo history sees either 2 or 3 actions. For example:

1. Create some text `foo`
2. Highlight and Ctrl + Shift+ B for bold
3. Notice that the text is now `**foo**` as expected
4. Press Ctrl + Z for undo
5. Notice that the text is now `**foo` instead of `foo`

with links you'll notice that each bracket and the set of parentheses are treated individually

2020-11-25 08:53 UTC, davidmhewitt commented
> It looks like for some reason undo history sees either 2 or 3 actions

@igordsm If I remember correctly, the solution to this is to call `TextBuffer.begin_user_action ()` at the start of an "action" (making something bold), then do all of the insertions and deletions necessary, then call `TextBuffer.end_user_action ()`. The undo manager should then treat that as one action.

2020-11-28 14:04 UTC, igordsm commented
@davidmhewitt Thank you. Just done that and it works as expected. @danrabbit undo/redo now work as expected.

![code-markdown-undo](https://user-images.githubusercontent.com/221446/100517472-70e03100-3169-11eb-80b3-161e0f77d31b.gif)

2020-12-15 21:26 UTC, danrabbit approved these changes
Works as expected! Nice job

2020-12-15 21:26 UTC, merged