Git diff
elementary/code pull request #914
Opened 2020-12-10 19:41 UTC by jeremypw

Supercedes and is based on #835

2021-05-03 17:32 UTC, jeremypw commented
The gutter currently only shows added and modified lines.  It is difficult to show deleted lines since, by definition, they do not appear in the SourceView. Possible ideas would be to get the GutterRenderer to show two colors if the line replaces a deleted line.

Another current limitation is that when a block of lines is modified, only the first one shows as "MODIFIED" - the rest show as "NEW". Working on a solution.

Result of commenting out a block:
![ModifiedBlock](https://user-images.githubusercontent.com/10513844/116910707-e29f3800-ac3d-11eb-9758-8d4302d628d2.png)

2021-05-04 09:02 UTC, jeremypw commented
After fixing modified block issue.
![ModifiedBlockFixed](https://user-images.githubusercontent.com/10513844/116981708-ccd25700-acbf-11eb-8fe0-ea6972ea1e40.png)

2021-05-04 09:04 UTC, jeremypw commented
Some improvement of efficiency may be possible and issue of showing lines were deleted (if needed) unresolved, but opening for review and ideas input.

2021-05-04 11:08 UTC, jeremypw commented
Showing there were some lines deleted before the `draw` functions
![DiffDeletedLines](https://user-images.githubusercontent.com/10513844/116994934-50487400-acd1-11eb-8db4-00bf17e3aba9.png)

2021-05-04 18:48 UTC, danrabbit commented
<details>
<summary>With this branch I immediately get a sefault:</summary>

```
Thread 1 "io.elementary.c" received signal SIGSEGV, Segmentation fault.
0x00007ffff7c826e1 in g_type_check_instance_is_fundamentally_a () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff7c826e1 in g_type_check_instance_is_fundamentally_a () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff7c5f942 in g_object_ref () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff1fd637f in  () at /usr/lib/x86_64-linux-gnu/io.elementary.code/plugins/markdown-actions/libmarkdown-actions.so
#3  0x00007ffff7c5a802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff7c6e814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff7c79bbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff7c7a0f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00005555555b024e in __lambda104_ (self=0x55555586c090, d=0x55555589ea80) at ../src/Services/PluginManager.vala:139
#8  0x00005555555b027b in ___lambda104__scratch_services_plugins_manager_hook_document (_sender=0x55555586c090, doc=0x55555589ea80, self=0x55555586c090) at ../src/Services/PluginManager.vala:138
#9  0x00007ffff7c5a802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff7c6e814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff7c79bbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff7c7ab9c in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x0000555555575688 in __lambda127_ (self=0x55555589a490, doc=0x55555589ea80) at ../src/MainWindow.vala:427
#14 0x000055555557587e in ___lambda127__scratch_widgets_document_view_document_change (_sender=0x555555970d30, document=0x55555589ea80, parent=0x555555970d30, self=0x55555589a490) at ../src/MainWindow.vala:426
#15 0x00005555555b9731 in g_cclosure_user_marshal_VOID__OBJECT_OBJECT (closure=0x555555ce0510, return_value=0x0, n_param_values=3, param_values=0x7fffffffc920, invocation_hint=0x7fffffffc8a0, marshal_data=0x0)
    at ../src/Widgets/DocumentView.vala:21
#16 0x00007ffff7c5a802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff7c6e814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff7c79bbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff7c7a0f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00005555555b8c4f in scratch_widgets_document_view_on_focus_in_event (self=0x555555970d30) at ../src/Widgets/DocumentView.vala:352
#21 0x00005555555b8227 in _scratch_widgets_document_view_on_focus_in_event_gtk_widget_focus_in_event (_sender=0x5555561b4f80, event=0x55555629e0b0, self=0x555555970d30) at DocumentView.c:1913
#22 0x00007ffff77ab4fb in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff7c5a802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff7c6e243 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff7c7947d in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff7c7a0f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff7755c23 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff77698e7 in gtk_widget_send_focus_change () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff776b9d0 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff776bc7a in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff7c5df03 in g_cclosure_marshal_VOID__OBJECTv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff7c5aa56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff7c79b48 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff7c7a0f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff7c5aa56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff7c79b48 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007ffff7c7a0f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff775a27a in gtk_widget_grab_focus () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00005555555a3b17 in scratch_services_document_focus (self=0x55555589ea80) at ../src/Services/Document.vala:568
#40 0x00005555555b700e in __lambda25_ (_data22_=0x5555557bd500, obj=0x55555589ea80, res=0x5555563050f0) at ../src/Widgets/DocumentView.vala:212
#41 0x00005555555b7087 in ___lambda25__gasync_ready_callback (source_object=0x55555589ea80, res=0x5555563050f0, self=0x5555557bd500) at ../src/Widgets/DocumentView.vala:209
#42 0x00007ffff7d5af49 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#43 0x00007ffff7d5bb3d in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#44 0x00005555555a1329 in scratch_services_document_open_co (_data_=0x555556338050) at ../src/Services/Document.vala:368
#45 0x000055555559f9fc in scratch_services_document_open_ready (source_object=0x555555e66680, _res_=0x555556337030, _user_data_=0x555556338050) at ../src/Services/Document.vala:317
#46 0x00007ffff7d5af49 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#47 0x00007ffff7d5bb3d in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#48 0x00007ffff70b6362 in  () at /lib/x86_64-linux-gnu/libgtksourceview-4.so.0
#49 0x00007ffff7d25e02 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#50 0x00007ffff7d5af49 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#51 0x00007ffff7d5af8d in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#52 0x00007ffff7ed904e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#53 0x00007ffff7ed9400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#54 0x00007ffff7ed94a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#55 0x00007ffff7d88fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#56 0x00005555555734bc in scratch_application_main (args=0x7fffffffdd88, args_length1=1) at ../src/Application.vala:166
#57 0x0000555555573509 in main (argc=1, argv=0x7fffffffdd88) at ../src/Application.vala:165
```
</details>

2021-05-04 21:05 UTC, jeremypw commented
@danrabbit I did get a crash from the plugins unless I installed the branch but I forgot to look into it.  You could try turning all plugins off if you don't want to install.

2021-05-04 21:06 UTC, jeremypw commented
I'll look into why plugins are causing a crash tomorrow.

2021-05-05 08:37 UTC, jeremypw commented
I have fixed the crash by reverting an unnecessary change although why it should cause a crash I couldn't determine. Something obscure about the way plugins and/or Vala works, I suppose.

2021-05-19 19:55 UTC, cassidyjames commented
Regarding deleted lines, you could potentially do a red indicator on the line above and below where it was removed, or even half a red indicator above and half a red indicator below, or something. But that could also be handled in a follow-up.

2021-05-20 17:26 UTC, jeremypw commented
@cassidyjames Thanks for the review. Yeah, I thought about doing the half-indicator thing but I thought it too complicated for this PR.  I'll fix the light style issue - I must remember to test in both dark and light styles!

2021-05-21 17:20 UTC, jeremypw commented
@cassidyjames Have fixed the background.  Need some input on whether the gutter is prominent (wide) enough and whether the colors are appropriate (e.g. saturated enough)

2021-05-25 17:48 UTC, danrabbit requested changes
Couple comments, but it seems to work as expected :)

2021-05-25 17:48 UTC, danrabbit commented on src/Services/MonitoredRepository.vala
> +                    color.parse ("#3689e6"); //Blueberry 500
can we get these colors from the source theme instead? It looks like themes should include colors for:

`diff:added-line`
`diff:removed-line`
`diff:changed-line`
`diff:special-case`
`diff:location`

2021-05-25 17:48 UTC, danrabbit commented on src/Services/MonitoredRepository.vala
> +            // var status_map = new Gee.HashMap<int, VCStatus> ();
commented line?

2021-05-25 17:48 UTC, danrabbit commented on src/Widgets/SourceGutterRenderer.vala
> +    public class SourceGutterRenderer : Gtk.SourceGutterRenderer {
For new classes, can we use inline namespace?
```suggestion
    public class Scratch.Widgets.SourceGutterRenderer : Gtk.SourceGutterRenderer {
```

2021-05-25 17:48 UTC, danrabbit commented on src/MainWindow.vala
> +           foreach (var action in action_accelerators.get_keys ()) {
looks like an accidental char deletion?

2021-05-25 17:48 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                monitored_repo.update_status_map ();
Nice job renaming that to something more clear

2021-05-26 16:19 UTC, jeremypw commented on src/Services/MonitoredRepository.vala
> +                    color.parse ("#3689e6"); //Blueberry 500
Definitely - I didn't know that.

2021-05-26 17:08 UTC, jeremypw commented on src/Services/MonitoredRepository.vala
> +                    color.parse ("#3689e6"); //Blueberry 500
Er - where do I find these themes/colors and how do I use them??  I couldn't find anything :disappointed:

2021-05-27 16:56 UTC, pongloongyeat commented on src/Services/MonitoredRepository.vala
> +                    color.parse ("#3689e6"); //Blueberry 500
Looks like stylesheet colours. See [here](https://github.com/elementary/stylesheet/blob/master/src/_palette.scss)

2021-06-02 16:57 UTC, danrabbit commented on src/Services/MonitoredRepository.vala
> +                    color.parse ("#3689e6"); //Blueberry 500
Hey sorry for not responding here earlier. These colors should be defined in the actual source style themes from the editor. It looks like there's a method [`Gtk.SourceStyleScheme.get_style ()`](https://valadoc.org/gtksourceview-4/Gtk.SourceStyleScheme.get_style.html) to grab these values. Here's some relevant code in Builder as well: https://github.com/GNOME/gnome-builder/blob/ea1c152c65e46cfed98081b5652c3ed7e36e51bf/src/libide/sourceview/ide-line-change-gutter-renderer.c#L85

2021-06-04 16:11 UTC, danrabbit requested changes
Looks good! One tiny nitpick

2021-06-04 16:11 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +        public Scratch.Services.MonitoredRepository? monitored_repo = null;
Seems like this can be:
```suggestion
        public Scratch.Services.MonitoredRepository? monitored_repo { get; private set; default = null; }
```

2021-06-04 19:17 UTC, danrabbit approved these changes
Let's go! Nice job! :rocket:

2021-06-04 19:17 UTC, merged