Allow launching with pkexec
elementary/code pull request #951
Opened 2021-02-10 22:41 UTC by danrabbit

And disallow launching with sudo so you don't get messed up permissions in your home

Fixes #202 
Fixes #932

2021-02-11 10:04 UTC, tintou commented
Ideally, we shouldn't even allow this and provide a `Write anyway` that would grant us write access to the file.

2021-02-11 19:51 UTC, danrabbit commented
@tintou for sure, but there's been an open issue report for this in both Code and Files for like years now so this is at least a little better than users trashing their home directory permissions

2021-02-24 17:17 UTC, jeremypw requested changes
This successfully preccents use of `sudo` and allows use of `pkexec` from the commandline.

Code does not currently give an indication when it runs as root and there is no "New Window as Administrator" option as yet but these could be further PRs.

One minor code issue.

2021-02-24 17:17 UTC, jeremypw commented on src/Application.vala
> +            };
Should `return 1;` after quit (), to avoid unnecessarily completing this function (which results in terminal errors at the moment)

2021-02-24 18:17 UTC, jeremypw approved these changes

2021-02-24 18:27 UTC, merged

2021-02-25 15:08 UTC, decathorpe commented
Uh, is it expected that this commit does not build yet?
(Due to missing translations for the new policy file, it looks like.)

2021-02-28 09:36 UTC, decathorpe commented
Since this PR was merged, my code builds fail with this error:

```
[6/134] /usr/bin/meson --internal msgfmthelper data/io.elementary.code.policy.in data/io.elementary.code.policy xml /builddir/build/BUILD/elementary-code-3.4.1+git210228.000514.6ffb5da7/po/extra
FAILED: data/io.elementary.code.policy 
/usr/bin/meson --internal msgfmthelper data/io.elementary.code.policy.in data/io.elementary.code.policy xml /builddir/build/BUILD/elementary-code-3.4.1+git210228.000514.6ffb5da7/po/extra
msgfmt: cannot locate ITS rules for data/io.elementary.code.policy.in
```