ProjectFolderItem: Add option to create new branch to context menu
elementary/code pull request #953
Opened 2021-02-13 17:58 UTC by jeremypw

Based on #915

2021-04-21 21:45 UTC, danrabbit requested changes
Left a number of comments. It's definitely cool to see some more advanced git features in here, but I think the experience in this branch feels pretty incomplete and not very predictable. It's pretty jarring to have things stashed or committed with no way to see what the commit message was or where it was stashed to. It kind of feels like this branch wants to do about 4 different things, but can't really do them well without becoming really big.

I think maybe it would be better to break it out into individual branches so we can work through the flow of each feature a little more

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +            entry.bind_property ("is-valid", create_button, "sensitive", BindingFlags.DEFAULT);
It looks like this needs to be `BindingFlags.SYNC_CREATE` or we get a sensitive button for an empty entry. Great use of ValidatedEntry here though! Very cool

```suggestion
            entry.bind_property ("is-valid", create_button, "sensitive", BindingFlags.SYNC_CREATE);
```

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                        var branch_item = new Gtk.MenuItem.with_label (_("New Branch")) {
Since this opens a dialog that takes more input, it should have ellipsis 
```suggestion
                        var branch_item = new Gtk.MenuItem.with_label (_("New Branch…")) {
```

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +            );
We should make sure to set the parent for this so it gets centered properly
```suggestion
            ) {
                transient_for = (Gtk.Window) get_toplevel ();
            };
```

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                _("The branch parent will be '%s'").printf (monitored_repo.current_branch_name),
These should use typographical quotes:
```suggestion
                _("Create a new local branch in “%s”").printf (file.name),
                _("The branch parent will be “%s”").printf (monitored_repo.current_branch_name),
```

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                dialog.add_action_widget (commit_button, 1);
Is there a reason you did it this way instead of:
```suggestion
                dialog.add_button (_("Stash"), 0);
                dialog.add_button (_("Commit"), 1);
```

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                    Gtk.ButtonsType.CANCEL
You may have to use `none` here to get the correct button order. It should be:

[Secondary Action] [Cancel] [Primary Action]

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                    case 1: //Commit
I guess we could use response type `APPLY` here?

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +        private void deal_with_uncommitted_changes () throws Ggit.Error, Error {
It seems like this dialog is thrown even when I would be able to switch branches without losing changes via Terminal

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                    _("Please choose what to do '%s'").printf (monitored_repo.current_branch_name),
This could probably be more explanatory. Something like:
```suggestion
                    _("Changes can be stashed for later to be applied to any branch, or they can be committed to “%s” before switching branches").printf (monitored_repo.current_branch_name),
```

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                    _("Branch '%s' has uncommitted changes").printf (monitored_repo.current_branch_name),
Typographical quotes
```suggestion
                    _("Branch “%s” has uncommitted changes").printf (monitored_repo.current_branch_name),
```

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                }
Instead of hiding and showing the item, the commit action should probably be enabled/disabled when this changes in `monitored_repo`. This will automatically set the item sensitivity and effect any keyboard shortcuts

2021-04-21 21:45 UTC, danrabbit commented on src/Services/MonitoredRepository.vala
> +            var message = ("Commit made at %s").printf (new DateTime.now_local ().to_string ());
Maybe we should hold off on this until we can provide an interface for creating a commit message? Or at least provide a better default commit message? For example, GitHub uses "Create %s" or "Update %s" (where `%s` is the affected filename) as its fallback.

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                        break;
I'm not sure this really makes a ton of sense. The only other response we can get here is `DELETE` which should be handled as `CANCEL`

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +            }
This doesn't seem to be handling actual errors. As far as I can tell the only thing this ever catches is when a user cancels the commit/stash dialog

2021-04-21 21:45 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                        monitored_repo.stash_all ();
This doesn't really seem great. The user is offered the option to stash, but there's no way to know where those changes were stashed or how to retrieve them later. Maybe we should save this functionality until we have a more fleshed out workflow for stashing

2021-04-27 08:37 UTC, jeremypw commented
Closed in favour of #997

2021-04-27 08:37 UTC, closed without merging