Project search
elementary/code pull request #971
Opened 2021-03-07 20:34 UTC by jeremypw

Simple implementation of a global search within the tracked files of a project

 - [x] Add "Project Search" option to project folder context menu
 - [x] Implement simple dialog to get search term and whether or not to treat as Regex expression
 - [x] Search tracked files (currently limited to `.vala` files)
 - [x] Count matches per file and display as badge
 - [x] Expand project folder to make matched files visible  
 - [ ] Allow input of filter for files to search
 - [ ] Show matches in view
 - [ ] Allow project search from existing search bar

2021-03-13 17:13 UTC, jeremypw commented
I think this OK for a review now. I have used it a while for my own work and it is quite useful.  There are a number of refinements possible but I do not want to over-complicate this PR.

2021-04-06 19:39 UTC, danrabbit requested changes
Definitely a handy feature! Left a few inline comments

2021-04-06 19:39 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +            search_item.activate.connect (() => { global_search (); });
This should probably be a GLib.Action so that we can assign a keyboard shortcut to it. It looks like VS Code uses `Ctrl + Shift + F` for global search

2021-04-06 19:39 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                                   bool recurse = true) {
It looks like you're only ever using one of these arguments, so we probably don't need all of this complexity

2021-04-06 19:39 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +            resizable: false,
`deletable` is already set in granite dialog.

Is there a reason not to allow this to be resizable?

2021-04-06 19:39 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +        border_width = 0;
shouldn't need to mess with this in Granite.Dialog

2021-04-06 19:39 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +            margin = 6
Instead of setting margins on each widget, you should use column and row spacing on the grid

2021-04-06 19:39 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
What does "tracked" mean?

2021-04-06 19:39 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +            active = true,
I'm not sure this is a good default. We should probably make the defaults more inclusive and let users make them more restrictive as necessary

2021-04-06 19:39 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +        var close_button = (Gtk.Button) add_button (_("Cancel"), Gtk.ResponseType.CANCEL);
It doesn't look like you ever reference the cancel button again, so it's probably not necessary to cache it

2021-04-08 09:59 UTC, jeremypw commented on src/FolderManager/ProjectFolderItem.vala
> +            search_item.activate.connect (() => { global_search (); });
The problem is that Code supports having more than one project open (which can be useful) so we need to determine which project is intended to be searched.  Presumably we could use whichever project the active document belongs to?

2021-04-08 10:01 UTC, jeremypw commented on src/FolderManager/ProjectFolderItem.vala
> +                                   bool recurse = true) {
This was intended for future development - I envisaged perhaps having some way to launch the global search from the searchbar.  But I can remove them for now.

2021-04-08 10:08 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +            resizable: false,
The layout of the dialog was temporary - I expect the design team will want to refine it. I didn't think dialogs are generally resizable but I can remove that.

2021-04-08 10:08 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +        border_width = 0;
OK

2021-04-08 12:10 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
It means git is tracking changes in the file.  Alternative?

2021-04-08 12:11 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +            active = true,
OK.  I intend to make user choices persist between uses later.

2021-04-08 13:26 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +        var close_button = (Gtk.Button) add_button (_("Cancel"), Gtk.ResponseType.CANCEL);
OK

2021-04-08 13:27 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
Should probably not show this switch when not a git repo.

2021-04-08 13:31 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +            margin = 6
OK

2021-04-08 14:53 UTC, jeremypw commented on src/FolderManager/ProjectFolderItem.vala
> +            search_item.activate.connect (() => { global_search (); });
OK implemented an action

2021-04-08 14:53 UTC, jeremypw commented on src/FolderManager/ProjectFolderItem.vala
> +                                   bool recurse = true) {
Removed unnecessary parameters

2021-04-08 14:54 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +            resizable: false,
Simplified layout and made resizable

2021-04-08 14:54 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +            active = true,
Changed default

2021-04-08 16:01 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
I have added a tooltip to explain what "Tracked" means.  Also added tooltips to other modes for consistency.

2021-04-08 17:07 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
Hm yeah, my first guess was maybe it has to do with indexing. Is this something that you have encountered as a real case or something that was just added because it's possible?

2021-04-08 18:18 UTC, cassidyjames requested changes
Brief UX review:

1. ~After performing a single search, I can no longer re-open the Project Search dialog—even after closing and re-opening Code. :o~ Apparently this only works when a text file is already open; it should work when there are no open files.

2. I like using badges in the sidebar to show the number of results, but I wonder if it's not obvious enough… at first, I performed a search and then sat there waiting for something more obvious to happen. I'm not sure what to do about that.

3. There's no obvious way to clear a search (including the badges in the sidebar) after performing it.

4. Should this be more integrated into the existing Find functionality? e.g. an option in the Find bar to "Find in current project" to trigger it?

5. We should badge parent folders with the total number of hits in their child directories, maybe even instead of expanding all directories that have hits.

6. We call the action "Find…" in the headerbar, but then call it a search bar… should we call this "Find in Project" instead of "Search Project"?

7. The menuitem should have an ellipsis since it's opening a dialog and the action is performed there.

Of course, some of these could be follow-up issues if it's too much scope creep.

2021-04-09 15:22 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
I have occasionally wanted to search the C files under the `build` folder for example, which are git-ignored so not tracked.  Although I suppose it would now be possible to search that folder specifically by using its context menu (that wasn't initially possible).  There may be other use cases I haven't thought of.  If you think that when searching a project folder users will only expect tracked files to be searched then I could omit this switch but it is possible users might be puzzled as to why some files in the folder were not searched.

2021-04-09 17:41 UTC, jeremypw commented
@cassidyjames Thanks for the review!

1. This is a consequence of using a simple MainWindow action for the menuitem.  If there are several project folders then MainWindow does not know which one to search.  I'll try adding a parameter to the action to get round this.
2. Maybe a toast showing the total number of matches and matching documents?  I was thinking about creating a search results document listing the files and lines containing matches. Geany does something similar (using a separate widget). That would be for another PR.
3. What else needs clearing other than the badges? The searchbar can be cleared in the usual way.  Is there a need to clear the badges - they will be cleared by the next search.  Maybe could clear them when the folder is collapsed?
4. This was planned for a future PR.
5. I disagree with not expanding the folders - I want to see the exact files where there are matches.  The total number of matches within a folder doesn't seem very useful.
6. OK, I can change that.
7. OK, will do

2021-04-09 18:41 UTC, jeremypw commented
@cassidyjames  I have addressed your points 1, 6 and 7.  The other points, especially 4 & 5, are best left to other PRs after some design thought.

2021-04-09 18:50 UTC, danrabbit commented
Yeah, I think eventually the design of the sidebar should change so that it's clear what project is the current focus of work. This will probably be important for git features as well.

I'm not sure if it's a pre-req for this branch, but it would probably make things easier

2021-04-09 18:59 UTC, jeremypw commented
You could have the same number of documents open from two projects so it is not obvious what the focus of work is other than which document is currently active (or maybe the last one that was changed?)

2021-04-20 17:01 UTC, jeremypw commented
@danrabbit @cassidyjames Are there any issues that cannot be left to another PR remaining?  I use this all the time for my own development and the main thing I would like would be persistence of the previous search, at least during the session, but I prefer to do that in another PR.

2021-04-20 23:38 UTC, danrabbit commented
@jeremypw Sorry, I've created some conflicts here while merging some of your other great fixes. Once those are resolved I'd be happy to take another look at this. Thank you for working on all of these things!

2021-04-21 16:09 UTC, jeremypw commented
At the moment global search via keyboard accelerator only works if there is a document open as the current document is used to determine the current project to search.

2021-04-21 16:39 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
My inclination would be to make the search as inclusive as possible and then we can come back and add more options if there's a demand for them in actual usage

2021-04-21 16:59 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
OK, I'll try using it with no filters for a while to see whether there are any serious drawbacks. The filters are based on what is supplied in Geany and what I have used in the past.

2021-04-21 17:38 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
Do you mean to keep the filters in the dialog but default them all to the most inclusive settings - or remove them altogether?  I notice you have pushed some fixes to this dialog, including the filters.

2021-04-21 17:42 UTC, danrabbit commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
My personal inclination would be to remove any of the filters that aren't immediately and obviously important. There's a few of these that seem a little hard to describe and may need some more copy writing thought if we want to include them, and then there's translation work etc that could be saved if they end up not being necessary. So we could save ourselves some work here by starting simpler

2021-04-22 08:56 UTC, jeremypw commented on src/Dialogs/GlobalSearchDialog.vala
> +        tracked_mode_index = scope_mode_button.append_text (_("Tracked"));
OK, I'll remove them altogether from the dialog (except, I would propose the Text/Regex switch and the Case Sensitive/Insensitive switch - which I use a lot).  I'll keep some of the infra-structure to make it easier to reinstate them as required.  One thought I had was to put the extra options in an "Advanced" revealer. I think most people familiar with git will understand these options easily enough but people using Code for other purposes do not need to see them.

2021-04-22 16:43 UTC, jeremypw commented
Revised Global Search Dialog:
![Screenshot from 2021-04-22 17 38 53](https://user-images.githubusercontent.com/10513844/115752366-eacfbb80-a391-11eb-96fa-f23ba7d6f5ae.png)

2021-04-22 17:02 UTC, jeremypw commented
For comparison, this is the equivalent dialog in Geany:

![Screenshot from 2021-04-22 18 01 08](https://user-images.githubusercontent.com/10513844/115755037-cc1ef400-a394-11eb-88e7-48e08684a4ea.png)

2021-04-26 22:25 UTC, danrabbit commented
This seems really good to me for a first version here. I think the only thing that feels weird is like Cassidy said there's no obvious way to clear the badges. What would you think about clearing the badges when the find bar is cleared? I feel like that should feel consistent since clicking a badged row would no longer show anything highlighted

It would probably be good to be consistent with the find bar and have case sensitivity disabled by default

Does Regex need to be able to be turned off? In my testing here, I have it enabled and it doesn't seem to be hindering my searches that don't contain any special regex syntax

2021-04-27 08:47 UTC, jeremypw commented
I don't think it can be excluded that a user might want to search for a literal string that does contain e.g. "^" or "$" or some other valid Regex.  In Geany at least you had to turn on Regex search if you wanted it.  The only drawback that I haven't yet address is that Regex search is not available in the headerbar so when the search term gets copied over it is not interpreted in the same way.  Similarly, at the moment, the "case sensitive" setting is not copied across to the headerbar.

I think clearing the badges when the search entry is cleared or closed is a good idea.  Will implement.

2021-04-27 16:59 UTC, danrabbit approved these changes
Nice work!

2021-04-27 16:59 UTC, merged