Add option to create new git branch
elementary/code pull request #997
Opened 2021-04-27 08:36 UTC by jeremypw

The option is added to the ProjectFolderItem/Branch submenu and is also accessible with the keyboard shortcut `<Control>B`

2021-04-27 08:38 UTC, tintou commented on src/FolderManager/FileView.vala
> +                var item = (ProjectFolderItem)child;
```suggestion
                unowned var item = (ProjectFolderItem)child;
```

2021-04-27 17:10 UTC, danrabbit requested changes
A few comments/suggestions :)

2021-04-27 17:10 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                    change_branch_menu.add (branch_item);
Instead of adding or removing the menuitem, we should enable/disable the action. Removing the menuitem when it might be expected can look like a bug, whereas an insensitive menuitem communicates that this option is not available

2021-04-27 17:10 UTC, danrabbit commented on src/MainWindow.vala
> +            action_accelerators.set (ACTION_NEW_BRANCH, "<Control>B"); //Git action - new branch
This comment seems redundant. If it isn't clear enough from the action name, perhaps the action name should include `GIT`

2021-04-27 17:10 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +            dialog.add_action_widget (create_button, Gtk.ResponseType.APPLY);
We can cache the return value of `add_button ()` so we don't need to use `add_action_widget ()`

```suggestion
            var create_button = (Gtk.Button) dialog.add_button (_("Create Branch"), Gtk.ResponseType.APPLY);
            create_button.get_style_context ().add_class (Gtk.STYLE_CLASS_SUGGESTED_ACTION);

            var entry = new Granite.ValidatedEntry.from_regex (new Regex ("^[a-z]+[a-z0-9--]*$"));
            entry.bind_property (
                "is-valid", create_button, "sensitive", BindingFlags.DEFAULT | BindingFlags.SYNC_CREATE
            );
```

2021-04-27 17:10 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                warning ("Error creating branch %s", e.message);
This should probably be a user facing error shouldn't it?

2021-04-27 18:01 UTC, jeremypw commented on src/MainWindow.vala
> +            action_accelerators.set (ACTION_NEW_BRANCH, "<Control>B"); //Git action - new branch
OK, its gone.

2021-04-27 18:10 UTC, danrabbit reviewed
It seems that creating a new branch fails if I don't have any documents open:
```
scratch_folder_manager_file_view_new_branch: assertion 'current_doc_file != NULL' failed
```

2021-04-27 18:10 UTC, danrabbit commented on src/FolderManager/ProjectFolderItem.vala
> +                var main_window = (MainWindow)(project_folder.view.get_toplevel ());
Would it be more reliable to use `Gtk.Application.get_active_window ()`?

2021-04-27 18:37 UTC, jeremypw commented on src/FolderManager/ProjectFolderItem.vala
> +                warning ("Error creating branch %s", e.message);
OK, done

2021-04-27 18:45 UTC, jeremypw commented on src/FolderManager/ProjectFolderItem.vala
> +                var main_window = (MainWindow)(project_folder.view.get_toplevel ());
Oh yes, that's easier.

2021-04-27 18:48 UTC, jeremypw commented
Both this and the project search branch assume there is an active document because that is how the active project folder is known.  Otherwise, when using the shortcut there is no way of telling which project you want the action to be performed on.  

Not sure what the best solution is for this, until we have an "active project" selector in the header.

2021-04-27 19:14 UTC, danrabbit commented
@jeremypw if I don't use the shortcut and right click on a toplevel folder, surely we know the project that we're intending to work with right?

2021-04-27 19:15 UTC, danrabbit commented
In any case, if we're unable to determine the correct project, there should probably be a user-facing error dialog for this

2021-04-27 21:44 UTC, jeremypw commented
The context menu uses the the same MainWindow action as the shortcut but there is currently no way of including the project folder as a parameter of the action. That is something that could be implemented as a stop gap for a more complete solution, if it is thought that is the way to go. And, as you say, a warning dialog could just be shown if the active project is not determinable

2021-04-28 16:50 UTC, danrabbit requested changes

2021-04-28 16:50 UTC, danrabbit commented on src/Dialogs/NewBranchDialog.vala
> +        });
Instead of this you can set `activates_default = true` on the entry

2021-04-28 16:50 UTC, danrabbit commented on src/Dialogs/NewBranchDialog.vala
> +            secondary_text = _("The barnch name must be lower-case, start with a letter, and be at least 3 characters");
typo
```suggestion
            secondary_text = _("The branch name must be lower-case, start with a letter, and be at least 3 characters");
```

2021-04-28 17:19 UTC, jeremypw commented on src/Dialogs/NewBranchDialog.vala
> +        });
The problem with that is that the default response is "CANCEL" so pressing Enter would always just cancel the dialog even if the entry contains a valid name.  The response returned needs to depend on whether the entry is valid or not.

2021-04-28 17:19 UTC, jeremypw commented on src/Dialogs/NewBranchDialog.vala
> +            secondary_text = _("The barnch name must be lower-case, start with a letter, and be at least 3 characters");
Good spot

2021-04-28 17:27 UTC, danrabbit commented on src/Dialogs/NewBranchDialog.vala
> +        });
Right so then you might need to make sure that the create branch button has `can_default`. Activating the entry shouldn't do two different things depending on its input

2021-04-28 17:35 UTC, jeremypw commented
A question: What should be done if there are 2 project folders open and the active document does not belong to either but there is an unfocused tab with a document from one of them?  At the moment, the warning dialog message is `"Open a document in a git project folder in the sidebar or use a project context menu."` which is not quite right. Is it worth trying to deal with this corner case?

2021-04-28 17:59 UTC, danrabbit commented
@jeremypw you know, would it be crazy to have a dropdown and ask the user to pick which project they intended if we can't figure it out?

2021-04-28 18:57 UTC, jeremypw commented
> would it be crazy to have a dropdown and ask the user to pick which project they intended if we can't figure it out?

Yes, that was going to be a future PR - I have put in place the infrastructure by passing a list of projects to the dialog.  I can implement in this PR if desired.

2021-04-28 19:22 UTC, danrabbit commented on src/Dialogs/NewBranchDialog.vala
> +            // new_branch_name_entry = new Granite.ValidatedEntry.from_regex (new Regex ("^[a-z].(?=[a-z0-9--]{2,}$)"));
Still need this?

2021-04-28 19:23 UTC, danrabbit approved these changes
In that case, let's merge what we've got and we can do that in a follow up branch :)

2021-04-28 19:33 UTC, merged